-- Schemat gry Lorein dla PostgreSQL / Supabase.
--
-- Konwersja z `sf555/DATABASE.sql` (MariaDB). Nazwy tabel i kolumn zostaly
-- zachowane co do znaku, zeby port kolejnych akcji z `req.php` byl
-- mechaniczny — kazde zapytanie z PHP ma tu swoj odpowiednik jeden do jednego.
--
-- UWAGA — trzy kolumny nosza nazwy zarezerwowane lub kolidujace w Postgresie
-- i w zapytaniach MUSZA byc w cudzyslowach:
--
--     user_data."group"      guild_chat."time"      witch."time"
--
-- Mapowanie typow:
--   int(11)          -> integer
--   bigint(20)       -> bigint
--   tinyint(4)       -> smallint      (wartosci 0/1 sa uzywane liczbowo,
--   tinyint(1)       -> smallint       wiec NIE zamieniamy ich na boolean)
--   tinytext/text    -> text
--   longtext         -> text
--   enum(...)        -> text + CHECK
--   AUTO_INCREMENT   -> GENERATED BY DEFAULT AS IDENTITY
--   datetime         -> timestamp

BEGIN;

-- ---------------------------------------------------------------- gracze --

CREATE TABLE user_data (
    user_id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name           text        NOT NULL,
    password            text        NOT NULL,
    lvl                 integer     NOT NULL DEFAULT 1,
    silver              bigint      NOT NULL DEFAULT 100,
    email               text        NOT NULL,
    email_validated     integer     NOT NULL DEFAULT 1,
    last_ip             varchar(30) NOT NULL,
    last_activ          varchar(30) NOT NULL,
    gchat_last          integer     NOT NULL DEFAULT 0,
    gattack_last        integer     NOT NULL DEFAULT 0,
    mush_donate         bigint      NOT NULL DEFAULT 0,

    face1               smallint    NOT NULL,
    face2               smallint    NOT NULL,
    face3               smallint    NOT NULL,
    face4               smallint    NOT NULL,
    face5               smallint    NOT NULL,
    face6               smallint    NOT NULL,
    face7               smallint    NOT NULL,
    face8               smallint    NOT NULL,
    face9               smallint    NOT NULL,
    face10              smallint    NOT NULL,
    golden_frame        smallint    NOT NULL DEFAULT 0,

    mushroom            integer     NOT NULL DEFAULT 5000,
    ssid                text        NOT NULL,
    reg_date            bigint      NOT NULL,
    enabled             text        NOT NULL DEFAULT 'yes' CHECK (enabled IN ('yes', 'no')),
    warned              text        DEFAULT 'no'           CHECK (warned  IN ('yes', 'no')),

    class               smallint    NOT NULL,
    race                smallint    NOT NULL,
    gender              smallint    NOT NULL,
    thirst              smallint    NOT NULL DEFAULT 6000,

    attr_str            integer     NOT NULL DEFAULT 10,
    attr_agi            integer     NOT NULL DEFAULT 10,
    attr_int            integer     NOT NULL DEFAULT 10,
    attr_wit            integer     NOT NULL DEFAULT 10,
    attr_luck           integer     NOT NULL DEFAULT 10,
    honor               integer     NOT NULL DEFAULT 100,

    dungeon_1           smallint    NOT NULL DEFAULT 0,
    dungeon_2           smallint    NOT NULL DEFAULT 0,
    dungeon_3           smallint    NOT NULL DEFAULT 0,
    dungeon_4           smallint    NOT NULL DEFAULT 0,
    dungeon_5           smallint    NOT NULL DEFAULT 0,
    dungeon_6           smallint    NOT NULL DEFAULT 0,
    dungeon_7           smallint    NOT NULL DEFAULT 0,
    dungeon_8           smallint    NOT NULL DEFAULT 0,
    dungeon_9           smallint    NOT NULL DEFAULT 0,
    dungeon_10          smallint    NOT NULL DEFAULT 0,
    dungeon_11          smallint    NOT NULL DEFAULT 0,
    dungeon_12          smallint    NOT NULL DEFAULT 0,
    dungeon_13          smallint    NOT NULL DEFAULT 0,
    tower_level         smallint    NOT NULL DEFAULT 1,

    copycat_lvl         varchar(11)  NOT NULL DEFAULT '150:150:150',
    copycat_str         varchar(100) NOT NULL DEFAULT '2056:887:884',
    copycat_dex         varchar(100) NOT NULL DEFAULT '884:861:1543',
    copycat_int         varchar(100) NOT NULL DEFAULT '861:1546:862',
    copycat_wit         varchar(100) NOT NULL DEFAULT '1417:1417:1418',
    copycat_luck        varchar(100) NOT NULL DEFAULT '1118:1118:1121',

    guild_id            smallint    DEFAULT 0,
    g_silverspent       bigint      NOT NULL,
    g_mushroomspent     bigint      NOT NULL,
    guild_rank          smallint    NOT NULL DEFAULT 0,
    guild_attack        smallint    NOT NULL DEFAULT 0,
    guild_defend        smallint    NOT NULL DEFAULT 0,
    guild_portal        varchar(30) NOT NULL DEFAULT '0',

    mount               smallint    NOT NULL DEFAULT 0,
    mount_dur           bigint      NOT NULL DEFAULT 0,
    user_desc           text        NOT NULL,

    medal_gladiator     integer     NOT NULL DEFAULT 0,
    medal_adventurer    integer     NOT NULL DEFAULT 0,
    medal_employment    integer     NOT NULL DEFAULT 0,
    medal_commerce      integer     NOT NULL DEFAULT 0,
    medal_bravery       integer     NOT NULL DEFAULT 0,
    medal_friendship    integer     NOT NULL DEFAULT 0,

    status              smallint    NOT NULL DEFAULT 0,
    status_end          integer     NOT NULL DEFAULT 0,
    status_extra        smallint    NOT NULL DEFAULT 0,

    quest_red_1         integer     NOT NULL DEFAULT 0,
    quest_red_2         integer     NOT NULL DEFAULT 0,
    quest_red_3         integer     NOT NULL DEFAULT 0,
    quest_gold_1        integer     NOT NULL,
    quest_location_1    smallint,
    quest_location_2    smallint    NOT NULL,
    quest_location_3    smallint    NOT NULL,
    quest_exp_1         integer     NOT NULL,
    quest_dur_1         integer     NOT NULL DEFAULT 2,
    quest_gold_2        integer     NOT NULL,
    quest_exp_2         integer     NOT NULL,
    quest_dur_2         integer     NOT NULL DEFAULT 2,
    quest_gold_3        integer     NOT NULL,
    quest_exp_3         integer     NOT NULL,
    quest_dur_3         integer     NOT NULL DEFAULT 2,

    exp                 bigint      NOT NULL DEFAULT 0,
    dungeon_time        bigint      NOT NULL DEFAULT 0,
    arena_time          bigint      NOT NULL DEFAULT 0,
    beers               integer     NOT NULL DEFAULT 0,
    quest_reroll_time   bigint      NOT NULL DEFAULT 0,
    shop_reroll_time    bigint      NOT NULL DEFAULT 0,

    toilet_time         bigint      NOT NULL DEFAULT 0,
    toilet              smallint    NOT NULL DEFAULT 0,
    toilet_full         smallint    NOT NULL DEFAULT 0,
    fill_level          integer     NOT NULL DEFAULT 0,
    fill_level_next     integer     NOT NULL DEFAULT 150,
    aura                smallint    NOT NULL DEFAULT 1,

    potion_id1          integer     NOT NULL,
    potion_id2          integer     NOT NULL,
    potion_id3          integer     NOT NULL,
    potion_value1       integer     NOT NULL,
    potion_value2       integer     NOT NULL,
    potion_value3       integer     NOT NULL,
    potion_time1        bigint      NOT NULL,
    potion_time2        bigint      NOT NULL,
    potion_time3        bigint      NOT NULL,

    magic_mirror        varchar(13) NOT NULL DEFAULT '0000000000000',
    album               integer     NOT NULL DEFAULT -1,
    album_data          text        NOT NULL,

    portal_act          integer     NOT NULL DEFAULT 1,
    portal_monster      integer     NOT NULL DEFAULT 1,
    portal_hp           bigint      NOT NULL DEFAULT 35938800,
    portal_time         varchar(4)  NOT NULL DEFAULT '',
    portal_regen_time   integer     NOT NULL DEFAULT 0,

    treasure            integer     NOT NULL DEFAULT 0,
    bonus               integer     NOT NULL DEFAULT 0,
    "group"             smallint    NOT NULL DEFAULT 1,
    color               smallint    NOT NULL DEFAULT 0,
    voucher_date        bigint      NOT NULL,
    chat_ban_until      integer     NOT NULL DEFAULT 0
);

-- Ranking sortuje po tych trzech kolumnach przy kazdym wejsciu do Sali Chwaly.
CREATE INDEX idx_user_data_ranking ON user_data (honor DESC, lvl DESC, user_id DESC);
CREATE INDEX idx_user_data_ssid    ON user_data (ssid);
CREATE INDEX idx_user_data_guild   ON user_data (guild_id);

CREATE TABLE user_fights (
    fight_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer   NOT NULL,
    target_id   integer   NOT NULL,
    success     text      NOT NULL,
    honor       integer   NOT NULL,
    fight_time  timestamp NOT NULL
);

CREATE INDEX idx_user_fights_user ON user_fights (user_id);

-- ----------------------------------------------------------- przedmioty --

CREATE TABLE items (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_type     smallint    NOT NULL,
    item_id       smallint    NOT NULL,
    dmg_min       integer     NOT NULL,
    dmg_max       integer     NOT NULL,
    atr_type_1    smallint    NOT NULL,
    atr_type_2    smallint    NOT NULL,
    atr_type_3    smallint    NOT NULL,
    atr_val_1     integer     NOT NULL,
    atr_val_2     integer     NOT NULL,
    atr_val_3     integer     NOT NULL,
    gold          integer     NOT NULL,
    mush          integer     NOT NULL,
    lvl           integer     NOT NULL DEFAULT 0,
    slot          smallint    NOT NULL,
    owner_id      integer     NOT NULL,
    toilet        integer     NOT NULL DEFAULT 0,
    enchant       varchar(30) NOT NULL DEFAULT '0',
    enchant_power varchar(100) NOT NULL DEFAULT '0',
    upgrade_level smallint    NOT NULL DEFAULT 0
);

CREATE INDEX idx_items_owner ON items (owner_id, slot);

-- Trzy tabele o identycznym ukladzie: asortyment obu sklepow i nagrody
-- z questow. W oryginale byly osobne — zachowujemy ten podzial, zeby port
-- akcji sklepow byl przepisaniem, a nie przeprojektowaniem.
CREATE TABLE items_shakes (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_type     smallint NOT NULL,
    item_id       smallint NOT NULL,
    dmg_min       integer  NOT NULL DEFAULT 0,
    dmg_max       integer  NOT NULL DEFAULT 0,
    atr_type_1    integer  NOT NULL,
    atr_type_2    integer  NOT NULL DEFAULT 0,
    atr_type_3    integer  NOT NULL DEFAULT 0,
    atr_val_1     integer  NOT NULL,
    atr_val_2     integer  NOT NULL DEFAULT 0,
    atr_val_3     integer  NOT NULL DEFAULT 0,
    gold          integer  NOT NULL DEFAULT 0,
    mush          integer  NOT NULL DEFAULT 0,
    slot          integer  NOT NULL,
    owner_id      integer  NOT NULL,
    enchant       bigint   NOT NULL,
    enchant_power bigint   NOT NULL
);

CREATE TABLE items_fidget (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_type     smallint NOT NULL,
    item_id       smallint NOT NULL,
    dmg_min       integer  NOT NULL DEFAULT 0,
    dmg_max       integer  NOT NULL DEFAULT 0,
    atr_type_1    integer  NOT NULL,
    atr_type_2    integer  NOT NULL DEFAULT 0,
    atr_type_3    integer  NOT NULL DEFAULT 0,
    atr_val_1     integer  NOT NULL,
    atr_val_2     integer  NOT NULL DEFAULT 0,
    atr_val_3     integer  NOT NULL DEFAULT 0,
    gold          integer  NOT NULL DEFAULT 0,
    mush          integer  NOT NULL DEFAULT 0,
    slot          integer  NOT NULL,
    owner_id      integer  NOT NULL,
    enchant       bigint   NOT NULL,
    enchant_power bigint   NOT NULL
);

CREATE TABLE items_tavern (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_type     smallint NOT NULL,
    item_id       smallint NOT NULL,
    dmg_min       integer  NOT NULL DEFAULT 0,
    dmg_max       integer  NOT NULL DEFAULT 0,
    atr_type_1    integer  NOT NULL,
    atr_type_2    integer  NOT NULL DEFAULT 0,
    atr_type_3    integer  NOT NULL DEFAULT 0,
    atr_val_1     integer  NOT NULL,
    atr_val_2     integer  NOT NULL DEFAULT 0,
    atr_val_3     integer  NOT NULL DEFAULT 0,
    gold          integer  NOT NULL DEFAULT 0,
    mush          integer  NOT NULL DEFAULT 0,
    quest         integer  NOT NULL,
    owner_id      integer  NOT NULL,
    enchant       bigint   NOT NULL,
    enchant_power bigint   NOT NULL
);

CREATE INDEX idx_items_shakes_owner ON items_shakes (owner_id);
CREATE INDEX idx_items_fidget_owner ON items_fidget (owner_id);
CREATE INDEX idx_items_tavern_owner ON items_tavern (owner_id);

CREATE TABLE tower_helper_items (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       integer      NOT NULL,
    tower_helper  smallint     NOT NULL,
    item_type     smallint     NOT NULL,
    item_id       smallint     NOT NULL,
    dmg_min       integer      NOT NULL,
    dmg_max       integer      NOT NULL,
    atr_type_1    smallint     NOT NULL,
    atr_type_2    smallint     NOT NULL,
    atr_type_3    smallint     NOT NULL,
    atr_val_1     integer      NOT NULL,
    atr_val_2     integer      NOT NULL,
    atr_val_3     integer      NOT NULL,
    gold          integer      NOT NULL,
    mush          integer      NOT NULL,
    slot          smallint     NOT NULL,
    toilet        integer      NOT NULL DEFAULT 0,
    enchant       varchar(30)  NOT NULL DEFAULT '0',
    enchant_power varchar(100) NOT NULL DEFAULT '0',
    upgrade_level smallint     NOT NULL DEFAULT 0
);

CREATE INDEX idx_tower_helper_user ON tower_helper_items (user_id);

-- --------------------------------------------------------------- gildie --

CREATE TABLE guilds (
    guild_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           text        NOT NULL,
    description    text        NOT NULL,
    chat           text        NOT NULL,
    leader_id      bigint      NOT NULL,
    honor          bigint      NOT NULL DEFAULT 100,
    silver         bigint      NOT NULL DEFAULT 1000,
    mushroom       bigint      NOT NULL DEFAULT 5000,
    fortress       smallint    NOT NULL DEFAULT 10,
    treasure       smallint    NOT NULL DEFAULT 0,
    instructor     smallint    NOT NULL DEFAULT 0,
    dung           smallint    NOT NULL DEFAULT 0,
    catapult       smallint    NOT NULL DEFAULT 3,
    portal_act     integer     NOT NULL DEFAULT 1,
    portal_monster integer     NOT NULL DEFAULT 1,
    portal_hp      bigint      NOT NULL DEFAULT 1003472384,
    portal_time    varchar(30) NOT NULL DEFAULT '0',
    coatofarms     varchar(50) DEFAULT '0D1306040E022802060A0B'
);

CREATE TABLE guild_chat (
    msg_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donator_name text     NOT NULL,
    guild_id     bigint   NOT NULL,
    "time"       text     NOT NULL,
    type         integer  NOT NULL DEFAULT 0,
    sender_id    bigint   NOT NULL,
    reciver_id   bigint   NOT NULL,
    msg          text     NOT NULL,
    donate_value bigint   NOT NULL DEFAULT 0,
    donate_type  text     NOT NULL,
    donator_lvl  bigint   NOT NULL DEFAULT 0
);

CREATE INDEX idx_guild_chat_guild ON guild_chat (guild_id, msg_id DESC);

CREATE TABLE guild_invites (
    invite_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id  integer NOT NULL,
    user_id   integer NOT NULL
);

CREATE TABLE guild_attacks (
    attack_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id     bigint NOT NULL,
    target_id    bigint NOT NULL,
    initiater_id bigint NOT NULL,
    attack_time  bigint NOT NULL,
    fight        text   NOT NULL
);

CREATE TABLE guild_attacks_archive (
    attack_id          bigint NOT NULL PRIMARY KEY,
    guild_id           bigint NOT NULL,
    target_id          bigint NOT NULL,
    fight_data         text   NOT NULL,
    fight_data_reverse text   NOT NULL,
    success            text   NOT NULL
);

-- -------------------------------------------------- komunikacja i reszta --

CREATE TABLE messages (
    msg_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id  bigint   NOT NULL,
    reciver_id bigint   NOT NULL,
    "time"     bigint   NOT NULL,
    subject    text     NOT NULL,
    msg        text     NOT NULL,
    read       smallint NOT NULL DEFAULT 0
);

CREATE INDEX idx_messages_reciver ON messages (reciver_id, msg_id DESC);

CREATE TABLE chat (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    message text    NOT NULL,
    date    bigint  NOT NULL
);

CREATE INDEX idx_chat_date    ON chat (date);
CREATE INDEX idx_chat_user_id ON chat (user_id);

CREATE TABLE banned_ips (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip varchar(45) NOT NULL,
    CONSTRAINT idx_ip_unique UNIQUE (ip)
);

CREATE TABLE vouchers (
    id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type   text         NOT NULL CHECK (type IN ('mushroom', 'silver')),
    amount integer      NOT NULL,
    used   integer      NOT NULL,
    code   varchar(255) NOT NULL
);

CREATE INDEX idx_vouchers_code ON vouchers (code);

CREATE TABLE witch (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donation_type   smallint NOT NULL DEFAULT 1,
    item_amount     bigint   NOT NULL DEFAULT 0,
    item_max_amount bigint   NOT NULL DEFAULT 1000,
    work            smallint NOT NULL DEFAULT 0,
    scroll_1        integer  NOT NULL,
    scroll_2        integer  NOT NULL,
    scroll_3        integer  NOT NULL,
    scroll_4        integer  NOT NULL,
    scroll_5        integer  NOT NULL,
    scroll_6        integer  NOT NULL,
    scroll_7        integer  NOT NULL,
    scroll_8        integer  NOT NULL,
    scroll_9        integer  NOT NULL,
    scrolls         integer  NOT NULL DEFAULT 1,
    "time"          integer  NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------- konfiguracja --

CREATE TABLE server_config (
    id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar(300) NOT NULL,
    value varchar(300) NOT NULL,
    CONSTRAINT uniq_server_config_name UNIQUE (name)
);

CREATE TABLE game_settings (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting varchar(300) NOT NULL,
    value   varchar(300) NOT NULL,
    CONSTRAINT uniq_game_settings_setting UNIQUE (setting)
);

-- ------------------------------------------------------------ dane bazowe --

INSERT INTO server_config (id, name, value) VALUES
    (1,  'SERVER_ID',        '1'),
    (2,  'HOST',             'localhost'),
    (3,  'LANGUAGE',         'pl'),
    (4,  'BACKGROUND',       '6'),
    (5,  'MAIL',             'admin@mail.com'),
    (6,  'SYSTEM_VERSION',   '555'),
    (7,  'GAME_VERSION',     '1.0.0'),
    (8,  'EVENT',            '5'),
    (9,  'EVENT_OCTOBERFEST','0'),
    (10, 'EVENT_DEALER',     '0'),
    (11, 'SEASON_EPICS',     '0');

INSERT INTO game_settings (id, setting, value) VALUES
    (1,  'POTION_DUR',              '72'),
    (2,  'FILL_EPIC',               '50'),
    (3,  'FILL',                    '25'),
    (4,  'MUSH_CHANCE',             '15'),
    (5,  'MUSH_CHANCE_EVENT',       '45'),
    (6,  'MUSH_DROP_FOUND',         '1'),
    (7,  'GAMBLER',                 '33'),
    (8,  'ITEMGEN_PMUSH_EPIC',      '15'),
    (9,  'ITEMGEN_PMUSH_TWOSTATS',  '10'),
    (10, 'ITEMGEN_PMUSH_LIFEPOT',   '15'),
    (11, 'GUILD_S_MINLEVEL',        '10'),
    (12, 'SERVER_RESTART',          '1589148000'),
    (13, 'FILL_POTION',             '10'),
    (14, 'QUEST_EXP',               '150'),
    (15, 'QUEST_GOLD',              '600'),
    (16, 'EPIC_CHANCE_SHOP',        '2'),
    (17, 'EPIC_CHANCE_SHOP_EVENT',  '8'),
    (18, 'WORK_MULTIPLIER',         '1'),
    (19, 'UNLIMITED_BEERS',         '0');

INSERT INTO witch (id, donation_type, item_amount, item_max_amount, work,
                   scroll_1, scroll_2, scroll_3, scroll_4, scroll_5,
                   scroll_6, scroll_7, scroll_8, scroll_9, scrolls, "time") VALUES
    (1, 1, 0, 100, 0, 51, 11, 71, 31, 81, 91, 101, 61, 41, 0, 1779919200);

-- Sekwencje IDENTITY musza ruszyc ponad recznie wstawione klucze.
SELECT setval(pg_get_serial_sequence('server_config', 'id'), 11, true);
SELECT setval(pg_get_serial_sequence('game_settings', 'id'), 19, true);
SELECT setval(pg_get_serial_sequence('witch',         'id'),  1, true);

COMMIT;
