/**
 * Napisy karczmy z oryginalu.
 *
 * PLIK GENEROWANY — nie poprawiaj recznie.
 * Zrodlo: sf555/lang/sfgame_pl.txt oraz stale TXT_* klienta Flash.
 * Generator: backend/scripts/gen-teksty-karczmy.mjs
 */

/** Kraina, w ktora wysyla zadanie — `quest_location_N` ma wartosc 1..21. */
export const KRAINY: string[] = [
  "Wedrzyj się w głąb Puszczy Zarośląskiej.",
  "Popłyń na Wyspę Trupiego Łba.",
  "Udaj się do Mrocznych Borów.",
  "Ruszaj w stronę Stepu Strapionych.",
  "Ruszaj na Pogórze Cienistej Skały.",
  "Ruszaj w podróż Dziewiczym Kanionem.",
  "Udaj się na Moczary Mary.",
  "Udaj się do miasta Propolis.",
  "Ruszaj w podróż w Góry Koronkowe.",
  "Marsz do Zmurszałego Lasu!",
  "Udaj się do Nigdylandii.",
  "Udaj się na Ugór Orków.",
  "Odnajdź dla mnie krainę Erogenii.",
  "Ruszaj do Magmakaronu.",
  "Ruszaj na Pustynię Przesłoneczną.",
  "Udaj się do Gnuśnogrodu.",
  "Udaj się na północ do miasta Teges.",
  "Niechaj cię droga zaprowadzi ku Czarnolasowi.",
  "Idź do grodu Maerwynn.",
  "Leć do Krainy Oz'Kurr.",
  "Ruszaj Traktem Trędowatych."
];

/** Podpisy w oknie wyboru zadania i u karczmarza. */
export const PODPISY = {
  "wybierzZadanie": "Wybierz zadanie:",
  "wynagrodzenie": "Wynagrodzenie:",
  "przyjmij": "Przyjmij",
  "wroc": "Wróć",
  "doswiadczenie": "Doświadczenie",
  "czasTrwania": "Czas trwania",
  "przerwij": "Przerwij",
  "pomin": "Pomiń",
  "awanturniczosc": "Awanturniczość",
  "paskAwanturniczosci": "Możesz odzyskać chęć na przygody, pijąc! Zagadnij karczmarza.",
  "piwoKup": "Napij się (1~P)",
  "piwoEfekt": "Awanturniczość +20",
  "piwoTytulOk": "Spragniony?",
  "piwoTytulNie": "Przykro mi, ale...",
  "piwoTekstOk": "Hej, kolego! Widzę po tobie, że nie pogardzisz trunkiem. To specjalność zakładu. Warzona zgodnie z rodzinną recepturą. Raz, dwa przywróci ci ochotę na podróże. Uważaj jednak, by nie przesadzić. Więcej niż dziesięć kufli powali nawet ogra.",
  "piwoTekstDosc": "...masz już dosyć, kolego. Trzeba znać umiar. Wróć jutro.",
  "piwoWypite": "Wypite dziś kufle:",
  "piwoTytulZaZdrowy": "Czego dusza pragnie?",
  "piwoTekstZaZdrowy": "Nie wolisz najpierw czegoś zrobić, zanim się tu zasiedzisz, kolego? Mój trunek stawia na nogi zmęczonych wędrowców. Nie widzę po tobie zmęczenia... ani śladów wędrówki. Zagadnij kogoś z gości. Na pewno ktoś tu znajdzie dla ciebie zadanie."
} as const;

/** Nazwy potworow — numer z serwera liczy od jedynki. */
export const POTWORY: string[] = [
  "Plugawy nietoperz",
  "Monstrualny nietoperz",
  "Nietoperz pylisty",
  "Mięsny golem",
  "Nieumarły zombie",
  "Obrzydliwy ożywieniec",
  "Rogacz ognisty",
  "Demon mrozu",
  "Kobra grzechocząca",
  "Kobra cienista",
  "Wijożmij",
  "Kobra plująca",
  "Niedźwiedź polarny",
  "Kłopotliwy miś",
  "Niedźwiedź brunatny",
  "Wściekły niedźwiedź brunatny",
  "Zielony T-Rex",
  "Czerwony T-Rex",
  "Szary T-Rex",
  "Śnieżny troll",
  "Nocny troll",
  "Górski troll",
  "Kamienny troll",
  "Siny sęp",
  "Sęp olbrzymi",
  "Szczur",
  "Szczur albinos",
  "Szczur ściekowy",
  "Rosiczka leśna",
  "Rosiczka bagienna",
  "Ghul nocny",
  "Siny ghul",
  "Ghul bagienny",
  "Raptor kłaposzczęki",
  "Raptor skaczący",
  "Raptor ryczący",
  "Wielka stopa",
  "Yeti",
  "Potwornie złowrogi zając",
  "Potwornie choleryczny zając",
  "Potwornie morderczy zając",
  "Potwornie różowy zajączek",
  "Potwornie okrutny zając",
  "Potwornie jadowity zając",
  "Czarnobrody",
  "Pirat John Pasat-Monsun",
  "Pirat Krwawonos",
  "Podły minotaur",
  "Nadęty minotaur",
  "Byczy kark",
  "Kamienny olbrzym",
  "Wulkaniczny olbrzym",
  "Zielony gnoll",
  "Szary gnoll",
  "Czerwony gnoll",
  "Pająk olbrzymi",
  "Okrutna tarantula",
  "Pająk drzewny",
  "Śnieżny lew",
  "Tygrys",
  "Pantera",
  "Lew górski",
  "Jaskiniowy skorpion",
  "Leśny skorpion",
  "Skorpion cienisty",
  "Ognisty skorpion",
  "Sukkub bezwstydny",
  "Bagienna nimfomanka",
  "Piekielna oblubienica",
  "Wiedźma",
  "Bordowy centaur",
  "Zielony centaur",
  "Szary centaur",
  "Banshee",
  "Wściekłe psisko",
  "Śnieżny wilk",
  "Wściekły wilk",
  "Posępny wilk",
  "Mulisty blob",
  "Piaskowy blob",
  "Oślizły blob",
  "Blob wulkaniczny",
  "Krwiożerczy wampir",
  "Podstępny wampir",
  "Wampir grozy",
  "Ohydny gremlin",
  "Okrutny gremlin",
  "Chciwy gremlin",
  "Zgniłozielony gremlin",
  "Szkaradny demon",
  "Złowrogi demon",
  "Odrażający demon",
  "Rozbójnik",
  "Rąbnięty rabuś",
  "Zły kradziej",
  "Bazyliszek",
  "Bazyliszek ognisty",
  "Mroczny obcy",
  "Piekielny obcy",
  "Toksyczny obcy",
  "Jeździec mroku",
  "Żywiołak ognia",
  "Szary gargulec",
  "Brązowy gargulec",
  "Krokodyl błotny",
  "Mroźny aligator",
  "Aligator cienisty",
  "Krokodyl mulisty",
  "Biały goryl",
  "Leśny goryl",
  "Goryl-góral",
  "Szkielet",
  "Szkielet voodoo",
  "Szaman voodoo",
  "Szkielet-żołnierz",
  "Szkielet-wojownik",
  "Nocna zmora",
  "Meduza z moczar",
  "Meduza mroku",
  "Słoniątko",
  "Lew",
  "Odyniec",
  "Dzik",
  "Żywiołak powietrza",
  "Burza piaskowa",
  "Rój plujek",
  "Okrutne drzewo",
  "Skażone drzewo",
  "Zjawa",
  "Glompf ognisty",
  "Wodny glompf",
  "Glompf bagienny",
  "Świniocyklop",
  "Cyklop piaskowy",
  "Piekielny cyklop",
  "Jaskiniowy cyklop",
  "Ośmiornica",
  "Don Kapiszi",
  "Szary dragor",
  "Parszywy drań",
  "Zawszony korsarz",
  "Hiena cmentarna",
  "Czarny upiór",
  "Upadły mnich",
  "Kapturnik",
  "Smok obłędu",
  "Dragor mrozu",
  "Piekielny dragor",
  "Olbrzymi smok",
  "Jaszczurzy siepacz",
  "Jaszczurzy rozbójnik",
  "Górski jaszczur",
  "Jaszczur z bagien",
  "Istota pozaziemska",
  "Przybysz z obcej planety",
  "Przybysz z kosmosu",
  "Mały zielony człowieczek",
  "Smok ciemności"
];

/**
 * Tytuly wypraw, zgrupowane wedlug rodzaju zadania.
 *
 * Wybor tytulu w zakresie liczy `tytulWyprawy()` — patrz `karczmaUklad.ts`.
 */
export const TYTULY_WYPRAW: Record<number, string[]> = {
  "1": [
    "Podziemne źródło",
    "Szewc",
    "Zabójcza ciekawość",
    "Tajemne wrota",
    "Niewiarygodne, a jednak!",
    "Niewiarygodna wędrówka",
    "Kamienny krąg magii",
    "Nawiedzone zamczysko",
    "Twoja stara szafa",
    "Portal do piekieł",
    "Złoty kufer",
    "Magiczny pierścień",
    "Stary człowiek",
    "Pieczara",
    "Ziołowa polana",
    "Szlachetny trunek",
    "Kość słoniowa",
    "Ostrożnie z zapałkami!",
    "Gigantyczny klejnot",
    "Kura Samograjka"
  ],
  "2": [
    "Filatelista",
    "Fajans",
    "Recykling",
    "Próżnia",
    "Bogactwa naturalne",
    "Porcelanowe słoniki",
    "Trendy",
    "Unikatowy amulet",
    "Dobroczynne zioła",
    "Czarni księża",
    "Sekretna ingrediencja",
    "Klapki na oczach",
    "Kwiaty morskie",
    "Obgryziona kość bohatera",
    "Motyla noga",
    "Frankenstein",
    "Ziemny golem",
    "Pusty kołczan",
    "Guru sekty",
    "Wielkie plany"
  ],
  "3": [
    "Landrynkę?",
    "Licencja na lizanie",
    "Drewniana szabelka",
    "Artefakt",
    "Znów ten wichajster",
    "Kula ognia",
    "Kminienie kminku",
    "Stare kości",
    "Krokodyle łzy",
    "Klucz do wer. beta. Tylko po co?",
    "Śmierdząca sprawa",
    "Przyszły milioner",
    "Niewyobrażalne",
    "Pod świętą egidą",
    "Magiczny miecz",
    "Złota zbroja",
    "Czapka niewidka",
    "Prawdziwa wiara",
    "Igła w stogu siana",
    "Tajemniczy kryształ"
  ],
  "5": [
    "Stare wiadro",
    "Torba orzeszków",
    "Kapelusz retro",
    "Niepozorna przesyłka",
    "Gumowa szabla",
    "Pusty kufer złota",
    "Kufer ołowiu",
    "Zleceniodawca w kufrze",
    "Lektyka",
    "Kolekcja znaczków",
    "Nowy komplet kół",
    "Podłożyć świnię",
    "Kowboj",
    "Owca",
    "Mordercza rozgrywka",
    "Wór mąki",
    "Zardzewiałe szyny",
    "Pióro",
    "Skurczona czacha",
    "Pukiel włosów",
    "Wiadro farby"
  ],
  "6": [
    "Syn kowala",
    "Ubogi staruszek",
    "Córka matki",
    "Mądry starzec",
    "Niewypłacalny kupiec",
    "Niewolnik kupca",
    "Ściemniający ściemniacz",
    "Weterynarz weteran",
    "Sędziwy czarnoksiężnik",
    "Karłowaty krasnolud",
    "Bezradny nadczłowiek",
    "Mój brat!",
    "Kapłan głębin",
    "Podwójny agent",
    "Piękna orczyca",
    "Człowiek w masce",
    "Naga kapłanka",
    "Wichajstry",
    "Urocze smoczątko",
    "Jedenastooka poczwara",
    "Ćwierćelf",
    "Wiejski głupek",
    "TO!"
  ]
};

/**
 * Zdania podsumowujace walke, po piec na kazdy stopien `fightStyle`.
 *
 * Indeks zewnetrzny to stopien: 0 gdy zwyciezcy zostalo ponad 80% zycia,
 * 1 ponad 40%, 2 ponad 20%, 3 ponizej. Wewnatrz klient losuje jedno
 * z pieciu.
 */
export const WYNIKI_WALKI: { wygrana: string[][]; przegrana: string[][] } = {
  "wygrana": [
    [
      "Wykonanie zadania przyszło z taką łatwością, że warto się zastanowić, czy w przyszłości w ogóle przyjmować takie zlecenia.",
      "Po zmiażdżeniu przeciwnika, możesz cieszyć się z następującej nagrody.",
      "Tyłek przeciwnika został porządnie skopany. Z niewzruszoną miną odbierasz swoją nagrodę.",
      "To przez takie zadania ludziska gadają, że w dzisiejszych czasach każdy obwieś może być bohaterem.",
      "Spuszczając przeciwnikowi łomot lewą ręką, prawą zasłaniasz sobie usta przy ziewaniu."
    ],
    [
      "Zgodnie z postanowieniami umowy, przeciwnik doznał uszczerbku na zdrowiu, a zleceniobiorca otrzymuje wynagrodzenie.",
      "Mówią: najpierw praca, potem przyjemności. Tym zleceniem udało ci się zaliczyć obie te rzeczy na raz.",
      "Brudna robota odwalona. Czas na zapłatę.",
      "Istna noc długich noży! Cóż, robota musi być wykonana.",
      "Zwycięstwo nie przyszło ci łatwo, ale za to rozsławi cię w najdalszych krańcach gminy."
    ],
    [
      "Z trudem udało ci się zgładzić przeciwnika. Za to nagrodę odbierasz z łatwością.",
      "Ten przeciwnik nie należał do tych łatwych, ale jakoś poszło.",
      "Za tobą ciężka potyczka. Ciężka jak truchło zgładzonego przez ciebie przeciwnika.",
      "Życie to nie bułka z masłem, a ten przeciwnik był twardy jak stuletni suchar. Jednak, jak na prawdziwego bohatera przystało, udało ci się go pokonać.",
      "Wyczerpująca walka i jeden szczęśliwy, choć lekko poturbowany zwycięzca -  ty!"
    ],
    [
      "Musisz opowiedzieć o tej walce w karczmie! To, że bohater opowieści ledwo wyszedł z niej cało, możesz pominąć.",
      "Wydawało ci się, że już z tobą koniec, ale jeszcze tym razem się udało. Jest też nagroda!",
      "Bardziej pomogło szczęście czy zdolności? Kto by się tam zastanawiał?! Ważne, że zwycięstwo jest po twojej stronie.",
      "Ledwo co! Warto się dobrze zastanowić przed przyjęciem kolejnej takiej samobójczej misji.",
      "Walka była bohaterska i zacięta do ostatniej sekundy. Odrobina szczęścia i zaciętość przechyliła jednak szalę na twoją stronę."
    ]
  ],
  "przegrana": [
    [
      "Pff! Przegrana z kretesem! Wszyscy się z ciebie śmieją.",
      "To było ciut ponad twoje możliwości, co?",
      "Chcesz zobaczyć niedorajdę? Spójrz w lustro!",
      "Następnym razem spróbuj użyć jakiegoś oręża. Kontratak zamiast uników też by nie zaszkodził.",
      "Gdyby tylko walka była dla ciebie równie ważna, co jęczenie, to wynik mógłby być zupełnie inny. A tak..."
    ],
    [
      "Lepiej daruj zleceniodawcy szczegóły tej porażki. Słabo!",
      "Całkowita porażka, żenada, strata czasu... Po prostu brak słów...",
      "Nie martw się, ktoś musiał spróbować. Choć mógłby to być ktoś, kto dałby z siebie więcej niż ty.",
      "Teraz wiesz, dlaczego przeciwnik tak ziewał przed walką. Nie chciał się do końca rozbudzać przed zmiażdżeniem cię.",
      "Spróbuj walczyć jeszcze gorzej, to może przeciwnik umrze ze śmiechu."
    ],
    [
      "Pojedynek nie był łatwy. Niestety dla ciebie odrobinę trudniejszy, niż dla przeciwnika. Może potrzebujesz nowej zbroi?",
      "Warto potrenować na wypadek takich okoliczności. Wiesz, bohaterowie czasem trenują. Dla leniwych jest też zbrojownia...",
      "Trochę szkoda łupu, ale spójrzmy prawdzie w oczy - to zlecenie zostało spartaczone.",
      "Niemalże, niemalże... A za «niemalże» nie ma nagrody. Co najwyżej rada: ucz się na błędach. Hm?",
      "Wytężony trening i lepsze wyposażenie mogłyby odmienić twój los. A tak co? Kaszana!"
    ],
    [
      "Do samego końca wynik tej batalii owiany był całunem niepewności. Jednak opadając, odsłonił on gorzką dla ciebie prawdę.",
      "Przeciwnik miał tyle szczęścia, że aż trudno w to uwierzyć. Niemniej trzeba.",
      "W ostatniej sekundzie walki, przeciwnik zadał ci decydujący cios, który zwalił cię z nóg.",
      "Teoretycznie szanse na zwycięstwo były takie same, jak na przegraną. Jednak praktyka nie teoretyzuje.",
      "Przeciwnik nie miał z tobą łatwej przeprawy. Ale odrobinę łatwiejszą, niż ty z nim."
    ]
  ]
};
