/**
 * Napisy karczmy z oryginalu.
 *
 * PLIK GENEROWANY — nie poprawiaj recznie.
 * Zrodlo: sf555/lang/sfgame_pl.txt oraz stale TXT_* klienta Flash.
 * Generator: backend/scripts/gen-teksty-karczmy.mjs
 */

/** Kraina, w ktora wysyla zadanie — `quest_location_N` ma wartosc 1..21. */
export const KRAINY: string[] = [
  "Wedrzyj się w głąb Puszczy Zarośląskiej.",
  "Popłyń na Wyspę Trupiego Łba.",
  "Udaj się do Mrocznych Borów.",
  "Ruszaj w stronę Stepu Strapionych.",
  "Ruszaj na Pogórze Cienistej Skały.",
  "Ruszaj w podróż Dziewiczym Kanionem.",
  "Udaj się na Moczary Mary.",
  "Udaj się do miasta Propolis.",
  "Ruszaj w podróż w Góry Koronkowe.",
  "Marsz do Zmurszałego Lasu!",
  "Udaj się do Nigdylandii.",
  "Udaj się na Ugór Orków.",
  "Odnajdź dla mnie krainę Erogenii.",
  "Ruszaj do Magmakaronu.",
  "Ruszaj na Pustynię Przesłoneczną.",
  "Udaj się do Gnuśnogrodu.",
  "Udaj się na północ do miasta Teges.",
  "Niechaj cię droga zaprowadzi ku Czarnolasowi.",
  "Idź do grodu Maerwynn.",
  "Leć do Krainy Oz'Kurr.",
  "Ruszaj Traktem Trędowatych."
];

/** Podpisy w oknie wyboru zadania i u karczmarza. */
export const PODPISY = {
  "wybierzZadanie": "Wybierz zadanie:",
  "wynagrodzenie": "Wynagrodzenie:",
  "przyjmij": "Przyjmij",
  "wroc": "Wróć",
  "doswiadczenie": "Doświadczenie",
  "czasTrwania": "Czas trwania",
  "przerwij": "Przerwij",
  "pomin": "Pomiń",
  "awanturniczosc": "Awanturniczość",
  "paskAwanturniczosci": "Możesz odzyskać chęć na przygody, pijąc! Zagadnij karczmarza.",
  "piwoKup": "Napij się (1~P)",
  "piwoEfekt": "Awanturniczość +20",
  "piwoTytulOk": "Spragniony?",
  "piwoTytulNie": "Przykro mi, ale...",
  "piwoTekstOk": "Hej, kolego! Widzę po tobie, że nie pogardzisz trunkiem. To specjalność zakładu. Warzona zgodnie z rodzinną recepturą. Raz, dwa przywróci ci ochotę na podróże. Uważaj jednak, by nie przesadzić. Więcej niż dziesięć kufli powali nawet ogra.",
  "piwoTekstDosc": "...masz już dosyć, kolego. Trzeba znać umiar. Wróć jutro.",
  "piwoWypite": "Wypite dziś kufle:",
  "piwoTytulZaZdrowy": "Czego dusza pragnie?",
  "piwoTekstZaZdrowy": "Nie wolisz najpierw czegoś zrobić, zanim się tu zasiedzisz, kolego? Mój trunek stawia na nogi zmęczonych wędrowców. Nie widzę po tobie zmęczenia... ani śladów wędrówki. Zagadnij kogoś z gości. Na pewno ktoś tu znajdzie dla ciebie zadanie."
} as const;

/** Nazwy potworow — numer z serwera liczy od jedynki. */
export const POTWORY: string[] = [
  "Plugawy nietoperz",
  "Monstrualny nietoperz",
  "Nietoperz pylisty",
  "Mięsny golem",
  "Nieumarły zombie",
  "Obrzydliwy ożywieniec",
  "Rogacz ognisty",
  "Demon mrozu",
  "Kobra grzechocząca",
  "Kobra cienista",
  "Wijożmij",
  "Kobra plująca",
  "Niedźwiedź polarny",
  "Kłopotliwy miś",
  "Niedźwiedź brunatny",
  "Wściekły niedźwiedź brunatny",
  "Zielony T-Rex",
  "Czerwony T-Rex",
  "Szary T-Rex",
  "Śnieżny troll",
  "Nocny troll",
  "Górski troll",
  "Kamienny troll",
  "Siny sęp",
  "Sęp olbrzymi",
  "Szczur",
  "Szczur albinos",
  "Szczur ściekowy",
  "Rosiczka leśna",
  "Rosiczka bagienna",
  "Ghul nocny",
  "Siny ghul",
  "Ghul bagienny",
  "Raptor kłaposzczęki",
  "Raptor skaczący",
  "Raptor ryczący",
  "Wielka stopa",
  "Yeti",
  "Potwornie złowrogi zając",
  "Potwornie choleryczny zając",
  "Potwornie morderczy zając",
  "Potwornie różowy zajączek",
  "Potwornie okrutny zając",
  "Potwornie jadowity zając",
  "Czarnobrody",
  "Pirat John Pasat-Monsun",
  "Pirat Krwawonos",
  "Podły minotaur",
  "Nadęty minotaur",
  "Byczy kark",
  "Kamienny olbrzym",
  "Wulkaniczny olbrzym",
  "Zielony gnoll",
  "Szary gnoll",
  "Czerwony gnoll",
  "Pająk olbrzymi",
  "Okrutna tarantula",
  "Pająk drzewny",
  "Śnieżny lew",
  "Tygrys",
  "Pantera",
  "Lew górski",
  "Jaskiniowy skorpion",
  "Leśny skorpion",
  "Skorpion cienisty",
  "Ognisty skorpion",
  "Sukkub bezwstydny",
  "Bagienna nimfomanka",
  "Piekielna oblubienica",
  "Wiedźma",
  "Bordowy centaur",
  "Zielony centaur",
  "Szary centaur",
  "Banshee",
  "Wściekłe psisko",
  "Śnieżny wilk",
  "Wściekły wilk",
  "Posępny wilk",
  "Mulisty blob",
  "Piaskowy blob",
  "Oślizły blob",
  "Blob wulkaniczny",
  "Krwiożerczy wampir",
  "Podstępny wampir",
  "Wampir grozy",
  "Ohydny gremlin",
  "Okrutny gremlin",
  "Chciwy gremlin",
  "Zgniłozielony gremlin",
  "Szkaradny demon",
  "Złowrogi demon",
  "Odrażający demon",
  "Rozbójnik",
  "Rąbnięty rabuś",
  "Zły kradziej",
  "Bazyliszek",
  "Bazyliszek ognisty",
  "Mroczny obcy",
  "Piekielny obcy",
  "Toksyczny obcy",
  "Jeździec mroku",
  "Żywiołak ognia",
  "Szary gargulec",
  "Brązowy gargulec",
  "Krokodyl błotny",
  "Mroźny aligator",
  "Aligator cienisty",
  "Krokodyl mulisty",
  "Biały goryl",
  "Leśny goryl",
  "Goryl-góral",
  "Szkielet",
  "Szkielet voodoo",
  "Szaman voodoo",
  "Szkielet-żołnierz",
  "Szkielet-wojownik",
  "Nocna zmora",
  "Meduza z moczar",
  "Meduza mroku",
  "Słoniątko",
  "Lew",
  "Odyniec",
  "Dzik",
  "Żywiołak powietrza",
  "Burza piaskowa",
  "Rój plujek",
  "Okrutne drzewo",
  "Skażone drzewo",
  "Zjawa",
  "Glompf ognisty",
  "Wodny glompf",
  "Glompf bagienny",
  "Świniocyklop",
  "Cyklop piaskowy",
  "Piekielny cyklop",
  "Jaskiniowy cyklop",
  "Ośmiornica",
  "Don Kapiszi",
  "Szary dragor",
  "Parszywy drań",
  "Zawszony korsarz",
  "Hiena cmentarna",
  "Czarny upiór",
  "Upadły mnich",
  "Kapturnik",
  "Smok obłędu",
  "Dragor mrozu",
  "Piekielny dragor",
  "Olbrzymi smok",
  "Jaszczurzy siepacz",
  "Jaszczurzy rozbójnik",
  "Górski jaszczur",
  "Jaszczur z bagien",
  "Istota pozaziemska",
  "Przybysz z obcej planety",
  "Przybysz z kosmosu",
  "Mały zielony człowieczek",
  "Smok ciemności"
];

/**
 * Tytuly wypraw, zgrupowane wedlug rodzaju zadania.
 *
 * Wybor tytulu w zakresie liczy `tytulWyprawy()` — patrz `karczmaUklad.ts`.
 */
export const TYTULY_WYPRAW: Record<number, string[]> = {
  "1": [
    "Podziemne źródło",
    "Szewc",
    "Zabójcza ciekawość",
    "Tajemne wrota",
    "Niewiarygodne, a jednak!",
    "Niewiarygodna wędrówka",
    "Kamienny krąg magii",
    "Nawiedzone zamczysko",
    "Twoja stara szafa",
    "Portal do piekieł",
    "Złoty kufer",
    "Magiczny pierścień",
    "Stary człowiek",
    "Pieczara",
    "Ziołowa polana",
    "Szlachetny trunek",
    "Kość słoniowa",
    "Ostrożnie z zapałkami!",
    "Gigantyczny klejnot",
    "Kura Samograjka"
  ],
  "2": [
    "Filatelista",
    "Fajans",
    "Recykling",
    "Próżnia",
    "Bogactwa naturalne",
    "Porcelanowe słoniki",
    "Trendy",
    "Unikatowy amulet",
    "Dobroczynne zioła",
    "Czarni księża",
    "Sekretna ingrediencja",
    "Klapki na oczach",
    "Kwiaty morskie",
    "Obgryziona kość bohatera",
    "Motyla noga",
    "Frankenstein",
    "Ziemny golem",
    "Pusty kołczan",
    "Guru sekty",
    "Wielkie plany"
  ],
  "3": [
    "Landrynkę?",
    "Licencja na lizanie",
    "Drewniana szabelka",
    "Artefakt",
    "Znów ten wichajster",
    "Kula ognia",
    "Kminienie kminku",
    "Stare kości",
    "Krokodyle łzy",
    "Klucz do wer. beta. Tylko po co?",
    "Śmierdząca sprawa",
    "Przyszły milioner",
    "Niewyobrażalne",
    "Pod świętą egidą",
    "Magiczny miecz",
    "Złota zbroja",
    "Czapka niewidka",
    "Prawdziwa wiara",
    "Igła w stogu siana",
    "Tajemniczy kryształ"
  ],
  "5": [
    "Stare wiadro",
    "Torba orzeszków",
    "Kapelusz retro",
    "Niepozorna przesyłka",
    "Gumowa szabla",
    "Pusty kufer złota",
    "Kufer ołowiu",
    "Zleceniodawca w kufrze",
    "Lektyka",
    "Kolekcja znaczków",
    "Nowy komplet kół",
    "Podłożyć świnię",
    "Kowboj",
    "Owca",
    "Mordercza rozgrywka",
    "Wór mąki",
    "Zardzewiałe szyny",
    "Pióro",
    "Skurczona czacha",
    "Pukiel włosów",
    "Wiadro farby"
  ],
  "6": [
    "Syn kowala",
    "Ubogi staruszek",
    "Córka matki",
    "Mądry starzec",
    "Niewypłacalny kupiec",
    "Niewolnik kupca",
    "Ściemniający ściemniacz",
    "Weterynarz weteran",
    "Sędziwy czarnoksiężnik",
    "Karłowaty krasnolud",
    "Bezradny nadczłowiek",
    "Mój brat!",
    "Kapłan głębin",
    "Podwójny agent",
    "Piękna orczyca",
    "Człowiek w masce",
    "Naga kapłanka",
    "Wichajstry",
    "Urocze smoczątko",
    "Jedenastooka poczwara",
    "Ćwierćelf",
    "Wiejski głupek",
    "TO!"
  ]
};
