/**
 * Nazwy przedmiotow z oryginalu.
 *
 * PLIK GENEROWANY — nie poprawiaj recznie.
 * Zrodlo: sf555/lang/sfgame_pl.txt oraz stale TXT_ITMNAME_* klienta Flash.
 * Generator: backend/scripts/gen-nazwy-przedmiotow.mjs
 */

/** Napisy z pliku jezykowego, tylko te potrzebne do nazw przedmiotow. */
export const TEKSTY: Record<number, string> = {
  119: "Blok",
  160: "Obrażenia",
  163: "Pancerz",
  1031: "Siła",
  1032: "Zręczność",
  1033: "Inteligencja",
  1034: "Wytrzymał.",
  1035: "Szczęście",
  1036: "Wszyst. cechy",
  3000: "Tłuk",
  3001: "Miecz-zabawka",
  3002: "Onucep",
  3003: "Sztacheta z gwoździem",
  3004: "Tasak",
  3005: "Sztylet podżeberny",
  3006: "Maczuga do sprzeczek",
  3007: "Topór podręczny",
  3008: "Nóż kuchenny",
  3009: "Buława do sprzeczek",
  3010: "Topór obusieczny",
  3011: "Pretensjonalny rapier",
  3012: "Porządny cep",
  3013: "Srebrny tomahawk",
  3014: "Długi miecz",
  3015: "Żelazna piącha",
  3016: "Katowski topór",
  3017: "Zadzior",
  3018: "Rozłupywacz czaszek",
  3019: "Twardy młot",
  3020: "Miecz królewski",
  3021: "Cierniak",
  3022: "Masywny młot",
  3023: "Pogromca smoków",
  3024: "Przeklęty topór",
  3025: "Miecz bohatera",
  3026: "Kontrargument",
  3027: "Prawa ręka śmierci",
  3028: "Oznaka statusu",
  3029: "Demoniczne ostrze",
  3050: "Taboret",
  3051: "Pokrywa od śmietnika",
  3052: "Drewniany puklerz",
  3053: "Tarcza ze złomu",
  3054: "Tarcza wojownika",
  3055: "Trupi puklerz",
  3056: "Puklerz iluminacji",
  3057: "Tarcza bohatera",
  3058: "Tarcza wodza",
  3059: "Paszcza demona",
  3100: "Kosz na śmieci",
  3101: "Blaszany bęben",
  3102: "Zbroja użytkowa",
  3103: "Zbroja turniejowa",
  3104: "Zbroja pyszałka",
  3105: "Pancerz zarozumialca",
  3106: "Zbroja płytowa",
  3107: "Pancerz bohatera",
  3108: "Zbroja wojownika",
  3109: "Zbroja zwycięzcy",
  3150: "Klapki",
  3151: "Gumofilce",
  3152: "Mokasyny",
  3153: "Zbrojne buty",
  3154: "Eleganckie buty",
  3155: "Buty wojownika",
  3156: "Buty rycerskie",
  3157: "Buty dowódcy",
  3158: "Buty bohatera",
  3159: "Królewskie buty",
  3200: "Usztywniacze",
  3201: "Stare rękawice",
  3202: "Nowe rękawice",
  3203: "Stylowe rękawice",
  3204: "Rękawice ochronne",
  3205: "Rękawice wojownika",
  3206: "Rękawice rycerskie",
  3207: "Rękawice szlachcica",
  3208: "Rękawice bohatera",
  3209: "Dusiciele smoków",
  3250: "Rondel",
  3251: "Blaszany hełm z korbką",
  3252: "Hełm z czepcem",
  3253: "Stalowe wiadro",
  3254: "Hełm urzędnika",
  3255: "Rogaty hełm",
  3256: "Hełm chaosu",
  3257: "Ostrohełm",
  3258: "Posępna maska",
  3259: "Posępny hełm",
  3300: "Stary pas",
  3301: "Wzmacniany pas",
  3302: "Stylowy pas",
  3303: "Pas wojownika",
  3304: "Elegancki pas",
  3305: "Kolczasty pas",
  3306: "Okazały pas",
  3307: "Markowy pas",
  3308: "Pas bohatera",
  3309: "Królewski pas",
  3350: "Drzewko zapachowe",
  3351: "Gangsterski łańcuch",
  3352: "Naszyjnik skryby",
  3353: "Amulet króliczka",
  3354: "Ego-naszyjnik",
  3355: "Amulet złotej rączki",
  3356: "Naszyjnik z grzybkiem",
  3357: "Stoper",
  3358: "Nieśmiertelnik",
  3359: "Naszyjnik bosmana",
  3360: "Naszyjnik z klejnotem",
  3361: "Naszyjnik runiczny",
  3362: "Róg obfitości",
  3363: "Naszyjnik z porożem",
  3364: "Klucz na sznurku",
  3365: "Babciny sznur pereł",
  3366: "Naszyjnik z kamieniem",
  3367: "Naszyjnik voodoo",
  3368: "Naszyjnik gapiącej się czaszki",
  3369: "Amulet iluminacji",
  3370: "Naszyjnik z kamieniem",
  3400: "Pętelka szczęścia",
  3401: "Pierścień odpustowy",
  3402: "Pierścień z blachy",
  3403: "Pierścień gumowej kaczuszki",
  3404: "Spiralny pierścień",
  3405: "Pierścień z gwiazdką",
  3406: "Szlachetny pierścień",
  3407: "Zdobiony pierścień",
  3408: "Lity pierścień",
  3409: "Pierścień z kamieniem",
  3410: "Zwój zaskrońca",
  3411: "Pierścień z diamentem",
  3412: "Pierścień podlotka",
  3413: "Pierścień z czaszką",
  3414: "Lśniąca obrączka",
  3415: "Pozerski pierścień",
  3450: "Oko",
  3451: "Brud",
  3452: "Roślina doniczkowa",
  3453: "Nadgryziona kanapka",
  3454: "Królewska peruka",
  3455: "Sztuczny wąs",
  3456: "Naparstek",
  3457: "Czerwony śledź",
  3458: "Święty Graal",
  3459: "Ekskluzywne czasopismo",
  3460: "Wydajne łajno",
  3461: "Ostro ciosany kamol",
  3462: "Kurze udko",
  3463: "Złamany oręż",
  3464: "Keczup",
  3465: "Żółtawe coś",
  3466: "Przedziwny artefakt",
  3467: "Srebrna łyżeczka",
  3468: "Obcinak do paznokci",
  3469: "Biustonosz gordyjski",
  3470: "Pognieciona karteczka",
  3471: "Sztuczny nochal",
  3472: "Plasterek",
  3473: "Przetykacz",
  3474: "Stylowe bryle",
  3475: "Obleśny patyczek do uszu",
  3476: "Czaszka Janusza",
  3477: "Czaszka Zygfryda",
  3478: "Czaszka Sinego Jurka",
  3479: "Smoczek",
  3480: "Czop",
  3481: "Bezużyteczny patyk",
  3482: "Żyletka",
  3483: "Uszatek",
  3484: "Trójkąt",
  3485: "Kości",
  3486: "Ząb czasu",
  3500: "Kule",
  3501: "Różdżka Magdaleny",
  3502: "Kryształowy kostur",
  3503: "Korzeń zła",
  3504: "Wielorybi kostur",
  3505: "Ognisty kostur",
  3506: "Kostur voodoo",
  3507: "Kostur astralny",
  3508: "Złowrogi paluch",
  3509: "Pożeracz dusz",
  3600: "Podomka",
  3601: "Szlafrok",
  3602: "Szata ucznia",
  3603: "Koszula",
  3604: "Elegancka koszula",
  3605: "Szata czeladnika",
  3606: "Szata adepta",
  3607: "Szata mistrza",
  3608: "Szata wielkiego mistrza",
  3609: "Hiper-wypasiona szata",
  3650: "Sandały",
  3651: "Kapcie",
  3652: "Kamasze",
  3653: "Obuwie błazna",
  3654: "Buty ucznia",
  3655: "Buty czeladnika",
  3656: "Buty adepta",
  3657: "Buty mistrza",
  3658: "Buty wielkiego mistrza",
  3659: "Buciory wielkiego mistrza",
  3700: "Jednorazowe rękawiczki",
  3701: "Rękawice z materiału",
  3702: "Rękawice skórzane",
  3703: "Rękawice ucznia",
  3704: "Pozerskie rękawice",
  3705: "Rękawice ucznia",
  3706: "Rękawice czeladnika",
  3707: "Rękawice adepta",
  3708: "Rękawice mistrza",
  3709: "Rękawice wielkiego mistrza",
  3750: "Czepek",
  3751: "Kaptur",
  3752: "Czapeczka",
  3753: "Czapka z antenką",
  3754: "Czapka ucznia",
  3755: "Kapelusz czeladnika",
  3756: "Kapelusz adepta",
  3757: "Kapelusz mistrza",
  3758: "Kapelusz wielkiego mistrza",
  3759: "Kaptur wielkiego mistrza",
  3800: "Sznur",
  3801: "Pas z materiału",
  3802: "Skórzany pas",
  3803: "Pas uczniowski",
  3804: "Ozdobny pas",
  3805: "Elegancki pas",
  3806: "Pas czeladnika",
  3807: "Pas adepta",
  3808: "Pas mistrza",
  3809: "Pas wielkiego mistrza",
  3850: "Proca",
  3851: "Łuk-zabawka",
  3852: "Krótki łuk",
  3853: "Kusza",
  3854: "Długi łuk",
  3855: "Łuk łowcy",
  3856: "Łuk bojowy",
  3857: "Kusza windykacji",
  3858: "Precyzyjny łuk",
  3859: "Perfidny truciciel",
  3950: "Łachmany",
  3951: "Tania kamizelka",
  3952: "Fajna kamizelka",
  3953: "Kubrak łowcy",
  3954: "Masywny pancerz",
  3955: "Szynel wędrowca",
  3956: "Elegancki pancerz",
  3957: "Pancerz pyszałka",
  3958: "Dizajnerski pancerz",
  3959: "Pancerz bohatera",
  4000: "Łapcie",
  4001: "Cuchnące buty",
  4002: "Pantofle",
  4003: "Porządne buciory",
  4004: "Porządne kamasze",
  4005: "Eleganckie kamasze",
  4006: "Kamasze wysokiej jakości",
  4007: "Dizajnerskie kamasze",
  4008: "Eleganckie kamasze",
  4009: "Kamasze bohatera",
  4050: "Mankiety",
  4051: "Rękawice z materiału",
  4052: "Sznurowane rękawice",
  4053: "Futrzane rękawice",
  4054: "Rękawice skórzane",
  4055: "Rękawice łowieckie",
  4056: "Wzmocnione rękawice",
  4057: "Rękawice strzeleckie",
  4058: "Rękawice ochronne",
  4059: "Pozerskie rękawice",
  4100: "Kawałek szmaty ze wstążką",
  4101: "Prymitywny kaptur",
  4102: "Lekki czepiec",
  4103: "Rogaty czepiec",
  4104: "Fajny czepiec",
  4105: "Fajny hełm",
  4106: "Elegancki hełm",
  4107: "Zbrojny hełm",
  4108: "Hełm samuraja",
  4109: "Hełm bohatera",
  4150: "Szary pas",
  4151: "Zwyczajny pas",
  4152: "Skromny pas",
  4153: "Kolczasty pas",
  4154: "Porządny pas",
  4155: "Pas wysokiej jakości",
  4156: "Dizajnerski pas",
  4157: "Kapitański pas",
  4158: "Pas pyszałka",
  4159: "Pas bohatera",
  4601: "słabeusza",
  4602: "gamonia",
  4603: "penetracji",
  4604: "naiwności",
  4605: "awanturnika",
  4606: "potulności",
  4607: "srogości",
  4608: "nadwagi",
  4609: "triatlonisty",
  4610: "majsterkowicza",
  4611: "przedsiębiorczości",
  4612: "mędrca",
  4613: "karateki",
  4614: "wynalazcy",
  4616: "pechowca",
  4617: "lepkich rąk",
  4618: "zdrajcy",
  4619: "talentu",
  4620: "ascezy",
  4621: "gibkości",
  4622: "rękodzieła",
  4624: "błogosławionego",
  4625: "rękoczynów",
  4626: "zagmatwania",
  4628: "pustelnika",
  4632: "czegokolwiek",
  4651: "osiłka",
  4652: "niepokoju",
  4653: "penetracji",
  4654: "czajenia",
  4655: "tyrana",
  4656: "potulności",
  4657: "srogości",
  4658: "pulchności",
  4659: "triatlonisty",
  4660: "majsterkowicza",
  4661: "przedsiębiorczości",
  4662: "mędrca",
  4663: "karateki",
  4664: "wynalazcy",
  4666: "niedorajdy",
  4667: "lepkich rąk",
  4668: "zdrajcy",
  4669: "talentu",
  4670: "ascezy",
  4671: "gibkości",
  4672: "rękodzieła",
  4674: "błogosławionego",
  4675: "rękoczynów",
  4676: "zagmatwania",
  4678: "pustelnika",
  4682: "czegokolwiek",
  4701: "brutalności",
  4702: "nerwowości",
  4703: "penetracji",
  4704: "mądrali",
  4705: "tyrana",
  4706: "potulności",
  4707: "srogości",
  4708: "nordic walkingu",
  4709: "triatlonisty",
  4710: "majsterkowicza",
  4711: "przedsiębiorczości",
  4712: "mędrca",
  4713: "karateki",
  4714: "wynalazcy",
  4716: "przesądności",
  4717: "lepkich rąk",
  4718: "zdrajcy",
  4719: "talentu",
  4720: "ascezy",
  4721: "gibkości",
  4722: "rękodzieła",
  4724: "błogosławionego",
  4725: "rękoczynów",
  4726: "zagmatwania",
  4728: "pustelnika",
  4732: "czegokolwiek",
  4751: "krwawej łaźni",
  4752: "potulności",
  4753: "penetracji",
  4754: "adepta magii",
  4755: "tyrana",
  4756: "potulności",
  4757: "srogości",
  4758: "półmaratończyka",
  4759: "triatlonisty",
  4760: "majsterkowicza",
  4761: "przedsiębiorczości",
  4762: "mędrca",
  4763: "karateki",
  4764: "wynalazcy",
  4766: "zwycięzcy",
  4767: "lepkich rąk",
  4768: "zdrajcy",
  4769: "talentu",
  4770: "ascezy",
  4771: "gibkości",
  4772: "rękodzieła",
  4774: "błogosławionego",
  4775: "rękoczynów",
  4776: "zagmatwania",
  4778: "pustelnika",
  4782: "czegokolwiek",
  4801: "srogości",
  4802: "kieszonkowca",
  4803: "penetracji",
  4804: "cwaniactwa",
  4805: "tyrana",
  4806: "potulności",
  4807: "srogości",
  4808: "maratończyka",
  4809: "triatlonisty",
  4810: "majsterkowicza",
  4811: "przedsiębiorczości",
  4812: "mędrca",
  4813: "karateki",
  4814: "wynalazcy",
  4816: "większego-szczęścia-niż-rozumu",
  4817: "lepkich rąk",
  4818: "zdrajcy",
  4819: "talentu",
  4820: "ascezy",
  4821: "gibkości",
  4822: "rękodzieła",
  4824: "błogosławionego",
  4825: "rękoczynów",
  4826: "zagmatwania",
  4828: "pustelnika",
  4832: "czegokolwiek",
  4851: "legendarnych supermocy",
  4852: "hazardzisty",
  4853: "penetracji",
  4854: "szczwanego lisa",
  4855: "tyrana",
  4856: "potulności",
  4857: "srogości",
  4858: "gruboskórności",
  4859: "triatlonisty",
  4860: "majsterkowicza",
  4861: "przedsiębiorczości",
  4862: "mędrca",
  4863: "karateki",
  4864: "wynalazcy",
  4866: "farciarza",
  4867: "lepkich rąk",
  4868: "zdrajcy",
  4869: "talentu",
  4870: "ascezy",
  4871: "gibkości",
  4872: "rękodzieła",
  4874: "błogosławionego",
  4875: "rękoczynów",
  4876: "zagmatwania",
  4878: "pustelnika",
  4882: "czegokolwiek",
  7000: "Przeklęty Szarpacz Dusz|\"Unikać kontaktu ze skórą.\"",
  7001: "Hak Klabaternika|\"Właściciel zmarł podczas przeciągania pod kilem.\"",
  7002: "Kruszyciel Kości Przemożnej Przemocy|\"Zwany czasem skalpelem barbarzyńcy.\"",
  7003: "Teksański Masakrator 2000|\"Morduje, masakruje, rozrywa#i parzy kawę.\"",
  7004: "Żółw na Kiju|\"Ten, który pokonał zająca.\"",
  7005: "Przepotężny Otwieracz Penetracji|\"Zamień wrogów w#przebojowe warzywa.\"",
  7006: "Skacowana Czacha Zaranna|\"Zły nastrój udziela się wszystkim.\"",
  7007: "Miecz Demonicznego Spojrzenia|\"Gdyby spojrzenie mogło zabić...#Ależ może!\"",
  7008: "Niezbędnik Pana Domu| \"Bardzo potężny artefakt# jeżeli potrafisz z niego korzystać\"",
  7009: "Wyrzutnia radioaktywna| \":\"Jej trujące opary# odstarszają potencjanych przeciwników\"",
  7010: "Wielki Nóż Rzeźnicki| \"Tylko rzeźnik wie, jak dobrze naostrzyć nóż\"",
  7011: "Pędzel Potłuczonego|\"Nie śmiej wątpić, że króliki#znoszą kolorowe jaja\"#- wesołych świąt wielkanocnych!",
  7012: "Siekiera Sieczki|\"Nie odkładaj na jutro tego,#co możesz zamordować dzisiaj\"#- wesołego Halloween!",
  7013: "Laska Podstępnego Pasterza|\"Za mną, nieświadome owieczki!#Drogę do rzeźni obierzmy!\"#- wesołych świąt!",
  7050: "Tarcza Strzeżonego Stróża|\"Strzeżonego stróża patron strzeżonych stróżów strzeże.\"",
  7051: "Tarcza Przyszłych Pokoleń|\"Zakaz wjazdu niżów demograficznych.\"",
  7052: "Tarcza Luminescencyjna|\"Oszczędność energii i trwałość#dzięki zastosowaniu diod LED.\"",
  7053: "Diaboliczny Diabeł Stróż|\"Każdego dnia obchodzi swoje 666. urodziny.\"",
  7054: "Kolczaste Łoże Fakira|\"Tarcza, jak również pomoc#do nauki akupunktury.\"",
  7055: "Mur|\"Nie potrzebujemy edukacji.#Nie potrzebujemy kontroli umysłów.\"",
  7056: "Voodoo-Grymas Odstręczania|\"Wroga broń instynktownie#się cofa.\"",
  7057: "Demoniczna tarcza deformacji|\"Ohyda.\"",
  7058: "Magnetyczny ekran odpychania|\"Nie nadaje się dla pacjentów z rozrusznikami serca\"",
  7059: "Krzywe zwierciadło deformacji|\"Twój przeciwnik padnie z wrażenia\"",
  7060: "Przenośny bunkier|\"Przydatny w każdej sytuacji\"",
  7061: "Malarska Paleta Króliczka|\"W zerówce króliczki chętnie#malują sceny masakry\"#- wesołych świąt wielkanocnych!",
  7062: "Ostrzegawcza Tarcza Morderczej Dyni|\"Gdy ujrzysz ową tarczę w borze,#Pojawi się dyńka – nikt ci nie pomoże\"#- wesołego Halloween!",
  7063: "Ładnie Opakowany Prezent Niechciany|\"Z imprezy wracasz z tarczą,#a czujesz się jak na tarczy\"#- wesołych świąt!",
  7100: "Chronicznie Chromowana Zbroja Ochronna|\"Pucu-pucu, glancu-glancu,#wrogów swych pokonasz w tańcu.\"",
  7101: "Pancerz Zniszczenia z Ognistej Stali|\"Najlepszy przyjaciel strażaków#i pogromców smoków.\"",
  7102: "Złoty Pancerz Hedonisty|\"Prawdziwy bohater nie walczy. On ma od tego ludzi.\"",
  7103: "Kostium Anonimowego Bohatera|\"W prawdziwym życiu#jest sławnym bohaterem.\"",
  7104: "Pancerz Nieposkromionego Gniewu|\"Noszony ze sztucznym uśmiechem.\"",
  7105: "Szklana zbroja przejrzystości|\"Aby, przy okazji, pokazać#podkoszulek.\"",
  7106: "Angielska skrzynka pocztowa w grze słów|\"! Angielski mail = zbroja = pocztowy = LOL 1\"",
  7107: "Demoniczna Zbroja Wielkiej Paszczy|\"Ejże! Twoja zbroja#właśnie zjadła moją...\"",
  7108: "Żółwia skorupa hydraulika|\"Jej poprzedni właściciel zbierał grzybki, by poczuć się wielkim\"",
  7111: "Upiorny Kostium Królika|\"Chętnie noszony przez ludzi złośliwych,#Aby wprowadzać zamęt krzykliwy!\"#- wesołych świąt wielkanocnych!",
  7112: "Płaszcz Skrytobójcy|\"Trzymaj się z dala od tych drani,#Co noszą w kieszeni węża i są szemrani!\"#- wesołego Halloween!",
  7113: "Strój z Bieguna Północnego|\"Kto nie podda się po dobroci,#Temu rózga skórę wymłóci\"#- wesołych świąt!",
  7150: "Chronicznie Chromowane Chodaki Ochronne|”Zaleca się polerować#raz w tygodniu.\"",
  7151: "Buty Beznadziei z Ognistej Stali|”Nadzieja umiera ostatnia,#najpierw umiera wróg.\"",
  7152: "Złote Platfusy Hedonisty|\"Z masażem stóp w standardzie.\"",
  7153: "Cybernetyczne Stopy Androida|\"Skoro nie zdziwili cię obcy i dinozaury...\"",
  7154: "Buty Nieposkromionego Gniewu|\"Dla prawdziwych dżentelmenów oraz dam.\"",
  7155: "Buty Jednorożca|\"Z przyczyn anatomicznych, nie jedno, ale dwa#zwierzęta musiały za to umrzeć.\"",
  7156: "Buty Lokomotywy Parowej|\"Ciężkie, ogromne i pot z nich spływa...\"",
  7157: "Demoniczne Buty Demonicznego Demona|\"Na piekielne przechadzki#po piekielnym piekle.\"",
  7158: "Ostrzane Buty|\"Solidne obuwie i otwieracz do konserw w jednym\"",
  7161: "Kapcie Króliczka|\"Choć złą sławą owiane są czarne koty,#Tym razem króliki zwiastują kłopoty\"#- wesołych świąt wielkanocnych!",
  7162: "Dyniowe Drewniaki|\"Kto choć raz w dynię wdepnął,#Zauważył, że mu miękko\"#- wesołego Halloween!",
  7163: "Buciory Grzańcopijcy|\"Kto się opije i siądzie na sanie,#Ten najpewniej żebra połamie\"#- wesołych świąt!",
  7200: "Chronicznie Chromowane Rękawice Ochronne|\"100% chromu.\"",
  7201: "Rękawice Upadku z Ognistej Stali|\"Ognista Stal powstaje#z połączenia ognia i stali.\"",
  7202: "Złote Łapska Hedonisty|\"Rozkoszne jest już#samo ich posiadanie.\"",
  7203: "Rękawice McGyvera|\"Posiadające Atest Adama Słodowego.\"",
  7204: "Rękawice Bezmiaru Niesprawiedliwości|\"Noszone w najdroższych kancelariach.\"",
  7205: "Żelazne Rękawice Bokserskie|\"W ringu niedozwolone,#w praktyce bardzo skuteczne.\"",
  7206: "Rękawice do Krojenia Chleba|\"I do mielenia wrogów#na bułkę tartą.\"",
  7207: "Rękawice Demonicznych Macek|\"Zwane też#Mackami Demonicznych Rękawic.\"",
  7208: "Tajemnicze Rękawice|\"W starych legendach zawsze tkwi ziarenko prawdy\"",
  7211: "Mięciutkie Rękawiczki|\"Kto chowa dłonie skrycie,#Często czyha na twe życie\"#- wesołych świąt wielkanocnych!",
  7212: "Nasadki na Palce Freddy'ego|\"Ostrza pod ręką i na ręce,#Z tym się odwiedza koszmary senne\"#- wesołego Halloween!",
  7213: "Rękawice Czuwania|\"Gdy paciorek masz już z głowy,#Warto posprzeczać się z tym i owym\"#- wesołych świąt!",
  7250: "Chronicznie Chromowany Hełm Ochronny|\"Glaca błyszczy!\"",
  7251: "Hełm Zniszczenia z Ognistej Stali|\"Groźny wygląd jeszcze nigdy nie był prostszy.\"",
  7252: "Złoty Łeb Hedonisty|\"Rozkosznie wygodny.\"",
  7253: "Hokejowa Maska Psychopaty|\"Hokej to krwawy sport.\"",
  7254: "Hełm Awanturnika|\"Nastawia pokojowo, koi nerwy.\"",
  7255: "Czarno-Żółta Maska Guślarza|\"Wariacja wersji czerwono-zielonej.\"",
  7256: "Bogato Zdobiony Hełm Konkurów|\"Skuteczny również jako#szczotka do podłogi.\"",
  7257: "Hełm Rogatego Demona|\"Ciekawe, co teraz robi#żona tego demona?\"",
  7258: "Uzbrojone gogle przewidywania| \"Dzięki nim ujrzysz ruchy swoich przeciwników\"",
  7261: "Długa Łycha|\"Kto zabawnie macha uszami,#Nie patyczkuje się z demonami\"#- wesołych świąt wielkanocnych!",
  7262: "Głowa z Dyni|\"Przebierz się za stracha na dzieci,#Wtedy monstra też strach obleci\"#- wesołego Halloween!",
  7263: "Czapka Oprawcy|\"Gdy mu uśmiech znika z twarzy,#Koniec żartów, czas powagi\"#- wesołych świąt!",
  7300: "Chronicznie Chromowany Pas Ochronny|\"Chroń chrom!\"",
  7301: "Pas Degradacji z Ognistej Stali|\"Jego wyjątkowe właściwości#są bezcenne.\"",
  7302: "Slipy Wątpliwej Świeżości|\"Noszą ślady ostatniej walki.\"",
  7303: "Obronny Pas Ataku|\"Korzystać tylko zgodnie z przeznaczeniem.\"",
  7304: "Pas Furiata|\"Trzyma nerwy w ryzach.\"",
  7305: "Pas Ostrych Krawędzi|\"Straszliwie bezpieczny i wygodny.\"",
  7306: "Pas Tarczowy|\"Tarcz nigdy za wiele.\"",
  7307: "Demoniczny Pas z Horroru|\"Dobrze trzyma dzięki#opatentowanej sprzączce mackowej.\"",
  7308: "Czepliwy fan| \"Pytanie brzmi: Czy kiedykolwiek się go pozbędziesz\"",
  7311: "Jajcarski Wieniec|\"Kolorowy, łatwo pęka,#Za to stylówa nieprzeciętna\"#- wesołych świąt wielkanocnych!",
  7312: "Pas Mroku|\"Załóż, idąc nocą do lasu,#A pozbędziesz się trwogi i strachu\"#- wesołego Halloween!",
  7313: "Pas św. Mikołaja|\"Kto się nim w pasie owinie,#Ma spore szanse nie utknąć w kominie\"#- wesołych świąt!",
  7500: "Różdżka Skurczonej Czachy o Szemranej Mocy|\"Ma niewielką pretensję w oczach.\"",
  7501: "Srebrna Kosa Ponurego Żniwiarza|\"Tegoroczny plon będzie obfity.\"",
  7502: "Ognista Różdżka Smoczego Jeźdźca|\"Marzenie każdego harcerza.\"",
  7503: "Różdżka Szarańczy|\"Gorączka mija jak tylko#jaja się wyklują.\"",
  7504: "Miotacz Ognia|\"Załączam gorące pozdrowienia.\"",
  7505: "Mokry Mop Ciecia|\"Ktoś musi zmywać te kałuże krwi.\"",
  7506: "Narzędzie Zbrodni Gitarowego Herosa|\"Z wbudowanym przyciskiem przesteru.\"",
  7507: "Skradziony Młódce Sztylet w Serce|\"Jego skuteczność dodatkowo#zwiększa krótka spódniczka.\"",
  7508: "Zabójcze narzędzie Klauna|\"Zabawa skończona!\"",
  7509: "Odkurzacz z dziurawym workiem| \"Czas zrobić gruntowny porządek z przeciwnikami\"",
  7510: "Cukierkowe laski zła|\"Szkodliwe dla zębów, i nie tylko\"",
  7511: "Pędzel Potłuczonego|\"Nie śmiej wątpić, że króliki#znoszą kolorowe jaja\"#- wesołych świąt wielkanocnych!",
  7512: "Siekiera Sieczki|\"Nie odkładaj na jutro tego,#co możesz zamordować dzisiaj\"#- wesołego Halloween!",
  7513: "Laska Podstępnego Pasterza|\"Za mną, nieświadome owieczki!#Drogę do rzeźni obierzmy!\"#- wesołych świąt!",
  7600: "Tajemna Szata Legendarnego Mistrza|\"Oczaruje każdego.\"",
  7601: "Szata Fidgeta|\"Wygląda na autentyczną.# Miejmy nadzieję, że ma drugą na zmianę.\"",
  7602: "Lodowo-Ogniowa Szata Eskimosa|”Najgorętszy towar na rynku.\"",
  7603: "Przeklęta Szata Dobroci|\"Odzienie i dylemat moralny w jednym.\"",
  7604: "Ponura Szata Ponurego Żniwiarza|\"Zegarmistrz światła purpurooowy...\"",
  7605: "Jaskrawa Kurtka Szołmena|\"Co to za pajac?\"",
  7606: "Schludny Frak Iluzjonisty|\"Jego schludność nie jest iluzją!\"",
  7607: "Peleryna Ducha|\"Trochę w niej duszno.\"",
  7608: "Starożytny kostium Mumii|\"Zawiera bardzo dużo konserwantów\"",
  7611: "Upiorny Kostium Królika|\"Chętnie noszony przez ludzi złośliwych,#Aby wprowadzać zamęt krzykliwy!\"#- wesołych świąt wielkanocnych",
  7612: "Płaszcz Skrytobójcy|\"Trzymaj się z dala od tych drani,#Co noszą w kieszeni węża i są szemrani!\"#- wesołego Halloween!",
  7613: "Strój z Bieguna Północnego|\"Kto nie podda się po dobroci,#Temu rózga skórę wymłóci\"#- wesołych świąt!",
  7650: "Tajemne Buty Maga Bitewnego|\"Czyżbyś wdepnął w manę?\"",
  7651: "Bohaterskie Kapcie|\"Nie mylić z Kapciami Bohatera.\"",
  7652: "Lodowo-Ogniowe Buty Sprzedawcy Lodów|\"By nawrzucać wrogom gał.\"",
  7653: "Buciory Posępnego Klauna|\"Koniec żartów.\"",
  7654: "Buty Próby Ognia|\"Dla ściemniaczy.\"",
  7655: "Pluszowe Pantofle Fajniuśności|\"Uwierają tylko w ego.\"",
  7656: "Kapcie Bezguścia|\"W połączeniu ze skarpetami#wyglądają zabójczo.\"",
  7657: "Gustowne Laczki Prestidigitatora|\"Dla absolwentów renomowanych abrakademii.\"",
  7658: "Stylowe laczki modnisia| \"Lepiej nie nosić w czasie deszczu\"",
  7661: "Kapcie Króliczka|\"Choć złą sławą owiane są czarne koty,#Tym razem króliki zwiastują kłopoty\"#- wesołych świąt wielkanocnych!",
  7662: "Dyniowe Drewniaki|\"Kto choć raz w dynię wdepnął,#Zauważył, że mu miękko\"#- wesołego Halloween!",
  7663: "Buciory Grzańcopijcy|\"Kto się opije i siądzie na sanie,#Ten najpewniej żebra połamie\"#- wesołych świąt!",
  7700: "Tajemne Rękawice Iluzjonisty|\"Zawartość many: 98%\"",
  7701: "Tajemny Krem Homeopatyczny|\"Efekty uboczne: świąd, supermoce.\"",
  7702: "Zielonopalczaste Rękawice Nosodłuba|\"Niezbędna pomoc odkrywcy.\"",
  7703: "Flisowe Rękawiczki Potępienia|\"Jeden z najbardziej mrocznych artefaktów!\"",
  7704: "Upiorne Bandaże Ozyrysa|\"Konserwują dłonie i wzmacniają uderzenie.\"",
  7705: "Pacynki do Macanki|\"Niechaj przemówią pięści!\"",
  7706: "Rękawice Ducha|\"Znika w nich dłoń!\"",
  7707: "Eleganckie Rękawice Magika|\"Na zręczne ręce.\"",
  7708: "Pacynkowe rękawiczki| \"Każdy palec - inna sztuczka, a w całej ręce magia\"",
  7711: "Mięciutkie Rękawiczki|\"Kto chowa dłonie skrycie,#Często czyha na twe życie\"#- wesołych świąt wielkanocnych!",
  7712: "Nasadki na Palce Freddy'ego|\"Ostrza pod ręką i na ręce,#Z tym się odwiedza koszmary senne\"#- wesołego Halloween!",
  7713: "Rękawice Czuwania|\"Gdy paciorek masz już z głowy,#Warto posprzeczać się z tym i owym\"#- wesołych świąt!",
  7750: "Paranoidalny Hełm Odbicia Promieni Laserowych|\"Wolnomyślicielstwo nabiera nowego znaczenia!\"",
  7751: "Anonimizator|\"Najnowsze osiągnięcie techniki szpiegowskiej.\"",
  7752: "Kapelusz Czarnoksiężnika|\"Zestaw bez królika.\"",
  7753: "Kapelusz Kapitana Korsarzy|\"Ciężko się w nim opędzić od#gadających papug.\"",
  7754: "Maska Voodoo Xecl'Poxle'a|\"Żartobliwie nazywana maską# tysiąca klątw.\"",
  7755: "Trójwymiarowe Okulary Daltonisty|\"Trawa jest zieleńsza#tylko w lewym oku.\"",
  7756: "Szacowna Peruka Jego Magnificencji|\"Nie wygląda aż tak głupio,#jeśli się wie, jak ją nosić.\"",
  7757: "Czarodziejski Kapelusz Osłupienia|\"Nie macie pojęcia,#jakie cuda w nim tkwią.\"",
  7758: "Kapelusz arystokracji| \"Pamiętaj, aby założyć go tylko jeden raz\"",
  7761: "Długa Łycha|\"Kto zabawnie macha uszami,#Nie patyczkuje się z demonami\"#- wesołych świąt wielkanocnych!",
  7762: "Głowa z Dyni|\"Przebierz się za stracha na dzieci,#Wtedy monstra też strach obleci\"#- wesołego Halloween!",
  7763: "Czapka Oprawcy|\"Gdy mu uśmiech znika z twarzy,#Koniec żartów, czas powagi\"#- wesołych świąt!",
  7800: "Dmuchane Koło Aquafobii|\"Raz na wodzie... raz na kole.\"",
  7801: "Pas Fidgeta|\"Jego właściciel był#'wielkim' magiem.\"",
  7802: "Lodowo-Ogniowy Pas Pracownika Chłodni|\"Dla zimnych drani!\"",
  7803: "Hawajski Kostium Niedzielnego Turysty|\"Gdy rum jest w cenie piwa.\"",
  7804: "Pas Zmutowanego Żółwia Ninja|\"Idealny, by zatknąć za nim nunczako.\"",
  7805: "Parasol Bezpieczeństwa Bankruta|\"Zbyt duży, by zawieść.\"",
  7806: "Pas Skondensowanej Magii|\"Słoik many gratis!\"",
  7807: "Niezależny Pas Wyniosłości|\"Kupowany dużo częściej,#niż Podległe Sznurówki Wasala.\"",
  7808: "Kosmyk włosów|\"Jedwabny i bez rozdwojonych końcówek\"",
  7811: "Jajcarski Wieniec|\"Kolorowy, łatwo pęka,#Za to stylówa nieprzeciętna\"#- wesołych świąt wielkanocnych!",
  7812: "Pas Mroku|\"Załóż, idąc nocą do lasu,#A pozbędziesz się trwogi i strachu\"#- wesołego Halloween!",
  7813: "Pas św. Mikołaja|\"Kto się nim w pasie owinie,#Ma spore szanse nie utknąć w kominie\"#- wesołych świąt!",
  7850: "Oddech Smoka|\"Gorączka sobotniej nocy#to przy nim zima stulecia.\"",
  7851: "Masakromat 5000|\"Idealny do wszelkiego typu masakr.\"",
  7852: "Neonowy Łuk Poznania|\"Używany też w innych miastach.\"",
  7853: "Biwakowy Łuk Łowcy|\"Rozpala serca wędrowców.\"",
  7854: "Łuk Filetowania Piranii|\"Uwaga! Może zawierać#resztki ości i zębów.\"",
  7855: "Rakietnica Realisty|\"Na idealistów, pesymistów, optymistów...\"",
  7856: "Chicken Master 3000|\"Model z ulepszoną celnością. Bez jaj!\"",
  7857: "Śmiercionośna Wuwuzela|\"Zwykła wuwuzela.\"",
  7858: "Harpun| \"Nadaje się również do polowania na delfiny oraz foki\"",
  7859: "Kusza snajpera| \"Jeden strzał, jedno trafienie\"",
  7860: "Kieszonkowa katapulta| \"Zawsze noś ją przy sobie\"",
  7861: "Łańcuch Marchwi|\"Kto potworom spierze gębę,#Wcina marchew na potęgę\"#- wesołych świąt wielkanocnych!",
  7862: "Siekiera Sieczki|\"Nie odkładaj na jutro tego,#co możesz zamordować dzisiaj\"#- wesołego Halloween!",
  7863: "Laska Podstępnego Pasterza|\"Za mną, nieświadome owieczki!#Drogę do rzeźni obierzmy!\"#- wesołych świąt!",
  7950: "Napierśnik Grubego Bodo|\"Nie wiadomo, kim był Gruby Bodo,#ale wiadomo, że to jego napierśnik.\"",
  7951: "Prześladowczy Pancerz Puszczańskiego Prześladowcy|\"Trudno prześledzić historię jego powstania.\"",
  7952: "Pancerz Pogromcy Demonów|”Idealny na polowanie na lisy i demony.\"",
  7953: "Skórzane Szelki Króla Barbarzyńców|\"Nie ma to jak skóra na nagie ciało.\"",
  7954: "Bawarskie Lederhose Piwosza|\"Rozporek czasem się zacina. To od częstego rozpinania.\"",
  7955: "Podniebna Kurtka Lotnika|\"Zestaw bez skrzydeł.\"",
  7956: "Trupia Kurtka Hieny Cmentarnej|\"Z najlepszych kawałków materiału.\"",
  7957: "Mordercza Kurtka z Mackami|\"Nosząc ją, nie należy#nikogo obejmować.\"",
  7958: "Smoczy Kostium Przytulania|\"Robi wrażenie!\"",
  7961: "Upiorny Kostium Królika|\"Chętnie noszony przez ludzi złośliwych,#Aby wprowadzać zamęt krzykliwy!\"#- wesołych świąt wielkanocnych!",
  7962: "Płaszcz Skrytobójcy|\"Trzymaj się z dala od tych drani,#Co noszą w kieszeni węża i są szemrani!\"#- wesołego Halloween!",
  7963: "Strój z Bieguna Północnego|\"Kto nie podda się po dobroci,#Temu rózga skórę wymłóci\"#- wesołych świąt!",
  8000: "Jaskrawożółte Gumofilce Jaskry|\"Idealny kamuflaż plantatora rzepaku.\"",
  8001: "Prześladowcze Pantofle Puszczańskiego Prześladowcy|\"A teraz powtórz to szybko dziesięć razy pod rząd.\"",
  8002: "Buty Pogromcy Demonów|\"By skopać demonie tyłki.\"",
  8003: "Skórzane Buty Króla Barbarzyńców|\"Sznurowane, więc zbyt skomplikowane#dla przeciętnego barbarzyńcy.\"",
  8004: "Skórzane Kozaki Dominacji|\"Wrogowie będą cię w nie#całować i jeszcze ci za to dziękować.\"",
  8005: "Kowbojki|\"Bo moda na nie wróci!\"",
  8006: "Podstępne Pasożyty Stóp|\"Żywią się twoim potem,#ale utrzymują ciepło. \"",
  8007: "Skrzydlate Buty Kuriera|\"30 cm ponad chodnikami...\"",
  8008: "Pantofle przyczajenia| \"Dzięki nim, skradanie się staje się o wiele prostsze\"",
  8011: "Kapcie Króliczka|\"Choć złą sławą owiane są czarne koty,#Tym razem króliki zwiastują kłopoty\"#- wesołych świąt wielkanocnych!",
  8012: "Dyniowe Drewniaki|\"Kto choć raz w dynię wdepnął,#Zauważył, że mu miękko\"#- wesołego Halloween!",
  8013: "Buciory Grzańcopijcy|\"Kto się opije i siądzie na sanie,#Ten najpewniej żebra połamie\"#- wesołych świąt!",
  8050: "Rękawice Nietoperzołaka|\"Skradzione z garderoby#sławnego superbohatera.\"",
  8051: "Prześladowcze Rękawice Puszczańskiego Prześladowcy|\"Bo kimże jest prześladowca bez nich?\"",
  8052: "Rękawice Pogromcy Demonów|\"Świetne również do głaskania kucyków.\"",
  8053: "Pieszczocha Króla Barbarzyńców|\"Ponieważ najprzyjemniej jest zabijać gołymi rękami.\"",
  8054: "Płonące Rękawice Ognia Piekielnego|\"Najdoskonalsze rękawice kuchenne.\"",
  8055: "Rękawice z Ulicy Wiązów|\"Pomagają oduczyć się#dłubania w nosie.\"",
  8056: "Koszmarne Pasożyty Dłoni|\"W sumie macki#są lepsze od palców.\"",
  8057: "Drogie Skórzane Rękawice Fircyka|\"Najlepsze, jakie można kupić.\"",
  8058: "Narzędzie samozniszczenia| \"Przydatne również na Twoich wrogów\" ",
  8061: "Mięciutkie Rękawiczki|\"Kto chowa dłonie skrycie,#Często czyha na twe życie\"#- wesołych świąt wielkanocnych!",
  8062: "Nasadki na Palce Freddy'ego|\"Ostrza pod ręką i na ręce,#Z tym się odwiedza koszmary senne\"#- wesołego Halloween!",
  8063: "Rękawice Czuwania|\"Gdy paciorek masz już z głowy,#Warto posprzeczać się z tym i owym\"#- wesołych świąt!",
  8100: "Drakoński Hełm Koziej Czaszki|\"A niech ktoś spróbuje nazwać cię rogaczem!\"",
  8101: "Prześladowczy Hełm Puszczańskiego Prześladowcy|\"Bo prześladować trzeba z głową.\"",
  8102: "Hełm Pogromcy Demonów|\"Demoniczny wygląd ma zmylić demona.\"",
  8103: "Skórzana Maska Nietypowych Preferencji|\"Specjalna ochrona przed pejczem.\"",
  8104: "Gustowne Sombrero|\"Buenos días, amigo!\"",
  8105: "Eksperymentalny Płaszcz Oblatywacza|\"W zestawie ze śmigłem awaryjnym.\"",
  8106: "Stymulator Mózgu|\"Jego cięty język#przyspiesza procesy myślowe.\"",
  8107: "Kapelusz Robina|\"Możesz dawać biednym...#Albo sobie.\"",
  8108: "Przenośne Obserwatorium | \"Teraz wiesz, co się dzieje wokół ciebie #\".",
  8111: "Długa Łycha|\"Kto zabawnie macha uszami,#Nie patyczkuje się z demonami\"#- wesołych świąt wielkanocnych!",
  8112: "Głowa z Dyni|\"Przebierz się za stracha na dzieci,#Wtedy monstra też strach obleci\"#- wesołego Halloween!",
  8113: "Czapka Oprawcy|\"Gdy mu uśmiech znika z twarzy,#Koniec żartów, czas powagi\"#- wesołych świąt!",
  8150: "Wielofunkcyjny Pas Nietoperzołaka|\"Wiele legendarnych funkcji.\"",
  8151: "Prześladowczy Pas Puszczańskiego Prześladowcy|\"Nigdy nie puszcza!\"",
  8152: "Pas Pogromcy Demonów|\"Demony będą trzymać się z dala.\"",
  8153: "Skórzane Portki Króla Barbarzyńców|\"0% bawełny.\"",
  8154: "Pas Szeryfa|\"Spójrz, jestem nieuzbrojony!\"",
  8155: "Zielony Zatruty Pas|\"Odtrutka za dodatkową opłatą.\"",
  8156: "Kompletny Pas Przetrwania|\"W zestawie z kuchenką gazową.\"",
  8157: "Pasożytniczy Pas|\"Wgryza się w ciało,#przez co pasuje idealnie.\"",
  8158: "Ogon tygrysa| \"Przebranie, w którym wygląda się naprawdę groźnie\"",
  8161: "Jajcarski Wieniec|\"Kolorowy, łatwo pęka,#Za to stylówa nieprzeciętna\"#- wesołych świąt wielkanocnych!",
  8162: "Pas Mroku|\"Załóż, idąc nocą do lasu,#A pozbędziesz się trwogi i strachu\"#- wesołego Halloween!",
  8163: "Pas św. Mikołaja|\"Kto się nim w pasie owinie,#Ma spore szanse nie utknąć w kominie\"#- wesołych świąt!",
  8300: "Klucz do Zbezczeszczonych Katakumb|”O! Klucz.#Ciekawe do czego?\"",
  8301: "Klucz do Kopalni Glorii|\"Wykonany przez krasnoludów,#znaleziony przez ciebie.\"",
  8302: "Klucz do Ruin Gnark|\"Zrabowany rabusiowi.\"",
  8303: "Piracki Klucz Licencyjny|\"Grota Korsarzy mieści się#w okrytej złą sławą Zatoce Korsarzy.\"",
  8304: "Łuskowaty Klucz Szmaragdowego Jaszczura|\"Święty artefakt starożytnej, okrutnej cywilizacji.\"",
  8305: "Klucz do Chorego Drzewa|\"Uważaj! Z pewnością#nie jest sterylny!\"",
  8306: "Piekielnie Gorący Klucz|\"Używać w rękawicy kuchennej.\"",
  8307: "Oszroniony Klucz Świątynny|\"Uwaga na odmrożenia!\"",
  8308: "Obłędny Klucz do Piramidy Szaleństwa|\"Gdy na niego patrzysz,#twój umysł kluczy przeróżnymi ścieżkami.\"",
  8309: "Klucz Posępnego Czerepu|\"Nie wygląda jakby prowadził#w gościnne miejsce.\"",
  8319: "Magiczny klucz do tajmniczej toalety| \"Kiedyś pijany gnom# uciekł z nim w siną dal\"",
  8320: "Magiczne Lustro Sobowtóra",
  8321: "Złowieszcze Jajo|\"Co też się może z tego wykluć?#Aż trudno cierpliwie wysiedzieć.\"",
  8322: "Przedziwne Jajo|\"Z zewnątrz niby zwyczajne.#Ale czy w środku jest żółtko?\"",
  8323: "Zaskakujące Jajo|\"Może królik#z czekolady coś o nim wie.\"",
  8329: "Odłamek Lustra Złowieszczego Kruka|\"Stłuczone lustro#oznacza 7 lat nieszczęścia.##A co się stanie,#gdy odłamek po odłamku#sklei się takie pechowe lustro?\"",
  8330: "Autorefleksyjny Odłamek Lustra|\"Rozpoznaj swoją ciemną stronę.#Uwolnij się ze świata luster#i spróbuj uzyskać#nad nim kontrolę.\"",
  8331: "Odłamek Lustra Niezdarności|\"Potężny i niestety nieco#niezdarny mag upuścił#pewne lustro.##Lepiej nie chodź boso, póki#nie odnajdziesz wszystkich#jego odłamków.\"",
  8332: "Sobowtórny Odłamek Lustra|\"Mówi się, że odbicie lustrzane#może zacząć żyć własnym życiem.##W najlepszym wypadku może#pomóc ci załatwić#kilka spraw na raz.##W najgorszym - będzie#dybało na twoje życie.\"",
  8333: "Półmroczny Odłamek Lustra|\"Mam cię na oku,#lustrzane odbicie!\"",
  8334: "Odłamek Lustra Przezorności|\"Odpowiednie lustro daje dobre#rozeznanie w panującej wokół sytuacji.##Możesz dzięki niemu#zauważyć rzeczy, które#wcześniej ci umykały.\"",
  8335: "Odłamek Lustra Podwójnej Moralności|\"Lustro, które wszystko podwaja?#Nawet moralność?##Do jakich nikczemności#może to doprowadzić?\"",
  8336: "Wielozadaniowy Odłamek Lustra|\"Lustro należało do pewnego#łapserdaka, który potrafił być w#dwóch miejscach jednocześnie.##W tym samym czasie był w#drodze i walczył na arenie.\"",
  8337: "(Nie)licencjonowany Odłamek Lustra|\"Z niejasnym statusem#prawnym odnośnie lustrzanej#kopii odbicia.\"",
  8338: "Dublujący Odłamek Lustra|\"Do wszelkich zastosowań,#których celem jest#podwajanie.\"",
  8339: "Odłamek Lustra Próżności|\"Przekleństwem posiadacza lustra#jest presja patrzenia weń.\"",
  8340: "Przemyślny Odłamek Lustra|\"Nie wiadomo jeszcze#do czego się przyda.#Ale do czegoś na pewno.\"",
  8341: "Replika Odłamka Lustra|\"Ten sfabrykowany przez mistrza-fałszerza#przedmiot wygląda niemal#jak prawdziwe lustro.\"",
  8342: "Złożony Odłamek Lustra|\"Można by tłumaczyć, do czego#służy, ale trwałoby to wieki.\"",
  8350: "Eliksir Odkręcacza Konfitur",
  8351: "Eliksir Żonglera",
  8352: "Eliksir Knajpianego Filozofa",
  8353: "Eliksir Grotołaza",
  8354: "Eliksir Laureata Nagrody Pocieszenia",
  8355: "Eliksir Stalowego Uścisku Dłoni",
  8356: "Eliksir Pana Miyagi",
  8357: "Eliksir Kujona",
  8358: "Eliksir Leśnika",
  8359: "Eliksir Zwycięzcy Lotto",
  8360: "Eliksir Wyciskania na Klatę",
  8361: "Eliksir Dryblingu",
  8362: "Eliksir Fizyka Molekularnego",
  8363: "Eliksir Maratończyka",
  8364: "Eliksir Rozbijacza Banków",
  8365: "Eliksir Nieśmiertelności",
  9112: "Klaser Dokładności",
  9113: "???",
  9114: "Znaleziono:#%1 / %2#%3%",
  9115: "Premia kolekcjonera",
  9116: "Potwory",
  9117: "Przedmioty wartościowe",
  9118: "Wyposażenie wojownika",
  9119: "Wyposażenie maga",
  9120: "Wyposażenie zwiadowcy",
  9121: "Do klasera trafiają na stałe wszystkie#znalezione i kupione przedmioty oraz te,#które miał przy sobie pokonany przeciwnik.##Trafiają tam też wszystkie pokonane potwory.##Od kompletności klasera zależy procentowa#premia do doświadczenia zdobywanego podczas zadań.",
  9150: "forever ;-)",
  9151: "Codziennie pomiędzy godziną 23 a 24 obowiązuje HAPPY HOUR!##Jeśli do tej pory nie zużyłeś jeszcze swojej Awanturniczości,#teraz możesz skrócić czas trwania misji.",
  9152: "Facebook",
  9153: "Google +",
  9154: "Obserwuj nas na Twitterze",
  10010: "Miecz Zemsty|Zaczaruj swoją broń,#aby zwiększyć obrażenia#krytycznych ciosów.",
  10030: "Broda Mario|Zaczaruj swój napierśnik,#aby podczas przygód#częściej znajdować grzyby.",
  10040: "36960-stopowe buty|Zaczaruj swoje obuwie,#aby skrócić czas#swych przygód.",
};

/** Poczatek tablicy nazw dla rodzaju 1..7, osobno dla kazdej klasy. */
export const BAZY_KLASOWE: Record<number, Record<number, number>> = {
  "1": {
    "1": 3000,
    "2": 3500,
    "3": 3850
  },
  "2": {
    "1": 3050,
    "2": 3550,
    "3": 3900
  },
  "3": {
    "1": 3100,
    "2": 3600,
    "3": 3950
  },
  "4": {
    "1": 3150,
    "2": 3650,
    "3": 4000
  },
  "5": {
    "1": 3200,
    "2": 3700,
    "3": 4050
  },
  "6": {
    "1": 3250,
    "2": 3750,
    "3": 4100
  },
  "7": {
    "1": 3300,
    "2": 3800,
    "3": 4150
  }
};

/** Poczatek tablicy nazw dla rodzajow wspolnych dla wszystkich klas. */
export const BAZY_WSPOLNE: Record<number, number> = {
  "8": 3350,
  "9": 3400,
  "10": 3450,
  "11": 8300,
  "12": 8350,
  "13": 9112,
  "14": 10000
};

/** Rodzaje bez przyrostka od cechy. */
export const BEZ_PRZYROSTKA: number[] = [11,12,13,14];

/** O tyle przesuwa sie tablica nazw przy przedmiocie epickim (obrazek >= 50). */
export const PRZESUNIECIE_EPICKICH = 4000;

/** Poczatek tablicy przyrostkow (TXT_ITMNAME_EXT). */
export const BAZA_PRZYROSTKOW = 4600;

/** Poczatek nazw cech przedmiotu (TXT_ITEM_ATTRIB_CLASSES). */
export const NAZWY_CECH = 1030;

/** Podpisy w podpowiedzi. */
export const TXT_OBRAZENIA = 160;
export const TXT_PANCERZ = 163;
export const TXT_BLOK = 119;
